- src/_sass/base.scss
- src/_sass/layout.scss
- src/_sass/tilt.scss
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/layouts:
bdeff658125e4d1a12875e92c696a07822b085ef (2019-01-29 15:26:57 -0500)
index: link styling
> index: link styling

- Gemfile
- Gemfile.lock
Hello @nicks,
Please review the following commits I made in branch nicks/layouts:
db8fb4d5eba3d63126b6b2ff925a80d9089b7d5f (2019-01-29 18:34:33 -0500)
add gemfiles symlinks to root dir
> add gemfiles symlinks to root dir

- src/_includes/head.html
- src/_sass/base.scss
- src/_sass/layout.scss
- src/_sass/tilt.scss
Hello @nicks,
Please review the following commits I made in branch nicks/fonts:
24685625e16be85b250185d0428a44f69ba06924 (2019-02-01 22:09:16 -0500)
improve fonts
> improve fonts

- src/_sass/layout.scss
- src/_sass/tilt.scss
Hello @nicks,
Please review the following commits I made in branch nicks/rev:
29a65bce826a2671fc15ccf743e57f55bf97e554 (2019-02-04 18:01:40 -0500)
tweak fonts a bit
> tweak fonts a bit

- src/_includes/head.html
- src/_sass/base.scss
- src/_sass/fx.scss
- src/_sass/layout.scss
- src/assets/js/fx.js
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/ch1483/onscroll:
2108f05dbd336f079438afbbc0db970c97534aae (2019-02-05 00:00:29 -0500)
add a scroll animation and disable font ligatures
> add a scroll animation and disable font ligatures

- src/_sass/layout.scss
- src/_sass/tilt.scss
- src/contact.md
Hello @nicks,
Please review the following commits I made in branch nicks/ch1479/contact:
a8fe0060f60194bc40ea5bbd7e8943ecd760f1d5 (2019-02-05 01:12:17 -0500)
contact: add contact page
> contact: add contact page

- src/_sass/fx.scss
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/bugfix:
deec915a0963b05402e79c31f59cd82e8187373e (2019-02-05 01:18:46 -0500)
bugfix: fix the button label
> bugfix: fix the button label

- src/_sass/base.scss
- src/_sass/layout.scss
- src/_sass/tilt.scss
- src/about.md
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/ch1481/mobile:
8f8d130f498e29efbacff6bb016a6d01642067f9 (2019-02-05 12:44:47 -0500)
initial pass at mobile styles
> initial pass at mobile styles

- src/404.html
- src/_sass/layout.scss
- src/contact.md
- src/thanks.md
Hello @nicks,
Please review the following commits I made in branch nicks/ch1487/form:
170086c2320f45e48183504b3ce28de8fdf4110f (2019-02-06 14:05:40 -0500)
wire up contact form
> wire up contact form

- src/_sass/layout.scss
- src/contact.md
Hello @nicks,
Please review the following commits I made in branch nicks/contact:
cc033eb82c01b24da587459a0726c612af70b8b6 (2019-02-06 16:14:13 -0500)
contact form: style fixes
> contact form: style fixes

- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/transitions:
0f27e3bc462f8779be3f301670e8cfa1108bc39e (2019-02-06 18:09:56 -0500)
add some css transitions
> add some css transitions

- src/_includes/header.html
- src/_sass/base.scss
- src/_sass/layout.scss
- src/_sass/tilt.scss
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/header:
066593eb8023f35b3fadc2bc39535cc4d40e79e5 (2019-02-07 16:59:19 -0500)
wide header and responsiveness fixes
> wide header and responsiveness fixes

- src/_sass/layout.scss
- src/contact.md
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/description:
596d95bbbf2e9fe2b6813811d3de3bc3ba9212b6 (2019-02-07 17:29:28 -0500)
update description text and spacing adjustments
> update description text and spacing adjustments

- docs/code_of_conduct.md
- docs/docker_compose.md
- docs/example_projects.md
- docs/faq.md
- docs/fast_build.md
- docs/first_example.md
- docs/helm.md
- docs/install.md
- docs/skaffold.md
- docs/tiltfile_concepts.md
- docs/tutorial.md
- src/_sass/syntax.scss
Hello @nicks,
Please review the following commits I made in branch nicks/content:
d73d5278873704bb07348794334013dbf195dc28 (2019-02-11 13:24:35 -0500)
docs: move docs into new format
> docs: move docs into new format

- docs/install.md
- src/_sass/layout.scss
- src/_sass/syntax.scss
- src/_sass/tilt.scss
Hello @nicks,
Please review the following commits I made in branch nicks/docscss:
52ef0680a4b6fff27ef27faa49b4059f9657cd38 (2019-02-11 19:30:56 -0500)
docs: tweak docs styles
> docs: tweak docs styles

- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/mobilemenu:
1c67070cc053824e5eff23d18f94b4830a1336a1 (2019-02-11 19:58:45 -0500)
animate the mobile menu
> animate the mobile menu

- src/_data/docs.yml
- src/_sass/base.scss
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/svg:
9a7a1cd9fffa9c2514ac88997980d6b9f2a57930 (2019-02-12 14:18:41 -0500)
minor style fixes
> minor style fixes

- Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/fix:
51368b19c14cf226f22e1559fe31b5a7ce67bd32 (2019-02-13 15:02:47 -0500)
remove a stray echo
> remove a stray echo

- src/_layouts/docs.html
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/editlink:
6362fb4eb102dfb434c142a19ca7baa28fd48aa9 (2019-02-13 16:13:10 -0500)
add an edit-on-github button
> add an edit-on-github button

- docs/search.html
- src/_layouts/docs.html
- src/_sass/layout.scss
- src/_sass/search.scss
- src/_sass/tilt.scss
Hello @nicks,
Please review the following commits I made in branch nicks/search:
a1eda4241f94067f194c1a319819e337acdf4471 (2019-02-13 17:27:55 -0500)
add a search form
> add a search form

- docs/nodejs_microservice_hotreloading.md
> docs: explain a bit more how hot reloading in node.js works

- _redirects
- api/api.py
- docs/_config.yml
- docs/footer.yml
- docs/index.md
- src/_config.yml
- src/_includes/api.html
- src/contact.md
Hello @nicks,
Please review the following commits I made in branch nicks/dev:
083c7a38dab336006296aa9f0087e32c02fe4e8a (2019-02-19 17:33:08 -0500)
move all the branding over to tilt.dev
> move all the branding over to tilt.dev

- docs/_config.yml
- docs/_redirects
- src/_config.yml
- src/_redirects
Hello @nicks,
Please review the following commits I made in branch nicks/redirects:
00ff3f36cd61b3983d917da23f80d1c60e182d5b (2019-02-19 17:47:02 -0500)
seo redirects
> seo redirects

- src/_redirects
Hello @nicks,
Please review the following commits I made in branch nicks/redirect:
b361e4a4df01ea43e57da75ac988fd8458ed12c2 (2019-02-20 14:24:06 -0500)
add windmill.engineering redirects as well
> add windmill.engineering redirects as well

- docs/faq.md
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/cliref:
80fd8c0d25c18d2b6f0484b8fb2a372d0dccf3f6 (2019-02-20 18:29:17 -0500)
faq: small changes to faq
> faq: small changes to faq

- api/api.py
- docs/helm.md
- docs/tiltfile_concepts.md
- docs/tutorial.md
- src/_includes/api.html
docs reflect syntax change in [PR #1191](https://github.com/windmilleng/tilt/pull/1191)
> update docs with new Yaml return type

- docs/faq.md
- src/_sass/layout.scss
- src/assets/js/links.js
Hello @nicks,
Please review the following commits I made in branch nicks/permalink:
011df56f94be3fe7182f1bc52236507f3b83f0f3 (2019-02-20 19:21:18 -0500)
add permalink arrows to faq
> add permalink arrows to faq

- docs/docker_compose.md
Please review the following commits I made in branch nicks/dc:
5fd0adcedacddb8d6dd92fa56c700ff047450d23 (2019-02-28 13:46:00 -0500)
refresh the docker-compose documentation
> refresh the docker-compose documentation

- docs/docker_compose.md
- src/_sass/syntax.scss
Please review the following commits I made in branch nicks/ch1811/dcdocs:
ceac41818009dd225ed29f8f4c376fb8001253b7 (2019-03-13 13:28:12 -0400)
docs: flesh out docker-compose documentation
> docs: flesh out docker-compose documentation

- docs/dependent_images.md
- docs/faq.md
- src/_data/docs.yml
Please review the following commits I made in branch nicks/ch1642/images:
e29ae5d0f1ff3d73ee6f4fd87e23718ad5f399b7 (2019-03-14 17:17:32 -0400)
docs: dependent images guide
> docs: dependent images guide

- docs/nested_fastbuild.md
Hello @nicks,
Please review the following commits I made in branch nicks/typo:
5631e39801e961ffc5fbaf8b43e1fd95a0915291 (2019-03-15 12:54:37 -0400)
docs: fix a typo
> docs: fix a typo

- docs/faq.md
Please review the following commits I made in branch nicks/ch1946/profiling:
c3b15b94f787574f1b36246cbb22d6c204ed26e2 (2019-03-22 17:11:06 -0400)
faq: add documentation on profiling
> faq: add documentation on profiling

- api/api.py
- src/_includes/api.html
This is just api docs to ensure we're on the same page. I've filed ch2047 for friendlier non-api docs.
This won't be merged until after the implementation is in master.
> api: add docs for live_update

- docs/live_update_tutorial.md
> balance parens in Live Update Tutorial

- Dockerfile
- Tiltfile
- base.dockerfile
- serve.yaml
- site.dockerfile
Please review the following commits I made in branch nicks/live:
bd251498ceffae56f0493eb772f4a3399517f406 (2019-04-10 13:24:18 -0400)
convert Tiltfile to new liveupdate
> convert Tiltfile to new liveupdate

- docs.dockerfile
I don't understand why this helps, but it unblocks me, and I'm not sure gaining that understanding is worth prioritizing at the moment.
> docs: work around issue #101

- src/_data/footer.yml
- src/_data/header.yml
- src/_sass/fx.scss
- src/_sass/layout.scss
- src/assets/svg/blog.svg
Hello @nicks,
da642effbd0d425189b0ac914329d032216eaa9d (2019-04-12 17:42:18 -0400)
new blog icon
> new blog icon

- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/copy2:
0e5fb971ae2476c1303c1604438e51e9d5f72b4d (2019-04-16 11:51:06 -0400)
landing page: fix some typos
> landing page: fix some typos

- src/_sass/base.scss
- src/_sass/layout.scss
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/copy3:
050a76f663dd9b6e0736c8fc9092989ae483884b (2019-04-17 14:18:10 -0400)
landing page: copy changes
> landing page: copy changes

- docs/faq.md
4728cde18989bb24bf37fc2e5a8cd271fdec6602 (2019-04-17 15:16:57 -0400)
add an faq item for microk8s
> add an faq item for microk8s

- docs/install.md
Hello @landism, @nicks,
Please review the following commits I made in branch maiamcc/bump-version-0.8.1:
6469af22841f95f6243af88a1f26ec4edb9e7bf2 (2019-04-26 13:56:33 -0400)
bump version to 0.8.1
> bump version to 0.8.1

- src/contact.md
Hello @nicks,
Please review the following commits I made in branch nicks/drip:
fcac3d090e263dab1be662e8b402edeb026eeeb6 (2019-04-30 16:45:47 -0400)
contact: turn formspree form into a drip form
> contact: turn formspree form into a drip form

- src/contact.md
Hello @nicks,
Please review the following commits I made in branch nicks/drip:
af9ff1f8bd3205ca396c04ec9e10428ce25d421a (2019-04-30 16:55:10 -0400)
use normal contact email address
> use normal contact email address

- docs/install.md
Hello @nicks,
Please review the following commits I made in branch nicks/bump:
58ec2aa59df43d941ceb6728f7e4bbda74c78bee (2019-05-02 18:40:47 -0400)
bump version
> bump version

- src/product.md
Please review the following commits I made in branch nicks/product:
41819725754605bb67c023f664e94c695f59120a (2019-05-10 14:00:27 -0400)
product job req
> product job req

- docs/docker_compose.md
- docs/helm.md
- docs/skaffold.md
- docs/tutorial.md
- src/_data/docs.yml
Hello @landism, @dbentley,
Please review the following commits I made in branch maiamcc/sidebar-links:
9f12eea52c80e25380e6a68e2b7202b7774f5339 (2019-05-10 11:54:25 -0400)
sidebar reorg/retitle some articles to make 'helm', 'skaffold' etc. pages make more sense
> sidebar reorg/retitle some articles to make 'helm', 'skaffold' etc. pages make more sense

- src/_sass/layout.scss
- src/kubecon.md
Hello @jazzdan, @yuindustries,
Please review the following commits I made in branch nicks/landing:
4e10cc77f703b060570bd36697e8a0dc7cc39e65 (2019-05-15 13:23:20 -0400)
add a kubecon landing page
> add a kubecon landing page

- src/product.md
Hello @nicks,
Please review the following commits I made in branch nicks/product:
2701c6af71eb0d5febf80b04db3fe8ecbb34a634 (2019-05-15 16:39:38 -0400)
add a cta link on the job req
> add a cta link on the job req

- src/post-subscribe.md
Hello @nicks,
Please review the following commits I made in branch nicks/subscribe:
6b6bdf7294ba965d9c1ca16968e5a286dc31b6fb (2019-05-15 16:48:01 -0400)
Add a post-subscribe page
> Add a post-subscribe page

- docs/install.md
- docs/upgrade.md
Hello @maiamcc, @landism,
Please review the following commits I made in branch nicks/version:
0375b576769a31b07dd41bd8acbca1924eae9b8b (2019-05-16 16:00:51 -0400)
docs: update install version
> docs: update install version

- src/contact.md
Hello @jazzdan, @yuindustries,
Please review the following commits I made in branch maiamcc/contact-link-longer:
8a0c8eeb397c86337bcfe6aa70e3be7dde6bc6ce (2019-05-17 12:39:09 -0400)
contact: link more text to our email (for accessibility/readability)
> contact: link more text to our email (for accessibility/readability)

- src/product.md
Hello @nicks,
Please review the following commits I made in branch nicks/product2:
b4963434b75d305109bd2d43ebab7d7d4e9a08ee (2019-05-17 16:13:40 -0400)
fix some minor typos
> fix some minor typos

- docs/install.md
- docs/upgrade.md
Please review the following commits I made in branch maiamcc/update-0.8.6:
e097a4342e01b9c28c5fbd96b315e9fbdf1a2aec (2019-05-20 18:21:45 -0400)
update versions to 0.8.6
> update versions to 0.8.6

- docs/index.md
- src/index.md
- src/kubecon.md
Hello @landism, @yuindustries,
Please review the following commits I made in branch maiamcc/new-demo-vid:
797a7952d6f3b51841d4ea1e92261241b9f11631 (2019-05-21 14:10:13 -0400)
use han's new demo video
> use han's new demo video

- src/kubecon.md
Hello @nicks,
Please review the following commits I made in branch nicks/open:
8d6e916b722e4009e97ae02fa90375624fd4a57b (2019-05-22 23:13:13 +0200)
update the kubecon landing page
> update the kubecon landing page

- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/kubecon:
9f17053a816c510e26ed3d75c42640cf5602d47c (2019-05-30 10:30:49 -0700)
remove kubecon plug
> remove kubecon plug

- docs/install.md
Please review the following commits I made in branch nicks/install:
79ebb1ab2ee4e9f03f7557392a3b983ab47f2e62 (2019-06-05 16:39:58 -0400)
Update the install instructions to point to the developer guide for from-source installs
> Update the install instructions to point to the developer guide for from-source installs

- docs/helm.md
Please review the following commits I made in branch nicks/helm:
eae9c8e43f187804bc54ba94a0235c7386dc6831 (2019-06-05 18:32:29 -0400)
helm: add examples
> helm: add examples

- blog/_posts/2019-05-03-thoughts-on-vscode-remote-development.md
- src/_layouts/blog.html
- src/_layouts/default.html
- src/_sass/layout.scss
- src/_sass/tilt.scss
Hello @nicks,
fddb58ba9c29f877bdc0f9615ccc2a00170b733e (2019-06-06 12:20:48 -0400)
blog: add title, subtitle styling
> blog: add title, subtitle styling

- src/_includes/api.html
Hello @nicks,
02df7ef2da18068bd04dfb7ca6219b0073074e16 (2019-06-06 14:22:07 -0400)
refresh api.html
> refresh api.html

- src/_sass/base.scss
Hello @nicks,
Please review the following commits I made in branch nicks/code:
bd6c29b17b347df8c4f9058ee5565bfbfc4b9944 (2019-06-06 14:36:32 -0400)
remove grey backgrounds from inline code, for consistency everywhere
> remove grey backgrounds from inline code, for consistency everywhere

- blog/_posts/2019-05-29-local-development-at-kubecon-eu.md
- blog/_posts/2019-06-06-observability-doesnt-work-in-dev.md
- src/_layouts/blog.html
- src/_sass/base.scss
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/blog2:
e8c2c8b6dd86bbb89f0aa34ac4048b93af6b8e38 (2019-06-06 16:21:03 -0400)
blog: feature image layouts
> blog: feature image layouts

- Tiltfile
- site.dockerfile
Please review the following commits I made in branch nicks/ignore:
a5a5840c226a1e8fa94846c161f62fe24f0e4b23 (2019-06-13 12:13:24 -0400)
tiltfile: use the new ignore param
> tiltfile: use the new ignore param

- src/_includes/header.html
Hello @nicks,
Please review the following commits I made in branch nicks/bloglink:
dacfb002302f53097463cec1fba54324a04f30d3 (2019-06-14 10:58:52 -0400)
fix a missing link
> fix a missing link

- blog/_config-dev.yml
- docs/_config-dev.yml
- serve.yaml
- src/_config-dev.yml
Hello @nicks,
Please review the following commits I made in branch nicks/health:
34e1b0c234ad18261e1e0421ffd52e26ad8b088f (2019-06-13 19:12:54 -0400)
tiltfile: bring back the health checks
> tiltfile: bring back the health checks

- src/_layouts/blog.html
- src/_sass/layout.scss
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/cta:
f904254d2e7bb98a8abbe926cc2c2e8a0695dab3 (2019-06-14 12:43:08 -0400)
blog: add call to action
> blog: add call to action

- blog/index.md
- src/_includes/preview.html
- src/_sass/layout.scss
- src/_sass/tilt.scss
Hello @nicks,
Please review the following commits I made in branch nicks/list:
077561da3da4ec01567dfc067fd8d727839d92a0 (2019-06-18 11:39:25 -0400)
blog: style listing page
> blog: style listing page

- blog/_posts/2017-09-12-introducing-windmill.md
- blog/_posts/2018-06-04-github-propelled-git-to-escape-velocity.md
- blog/_posts/2018-12-05-tilt-is-the-start-sh-script-of-my-dreams.md
- blog/_posts/2019-04-30-tilt-v0-8-release.md
- src/_includes/preview.html
Hello @nicks,
Please review the following commits I made in branch nicks/icon:
128d444df05cb1f443e0e6d022cbbe525b2c266b (2019-06-18 17:42:36 -0400)
blog: handle different image styles
1f6f8d04cefd56e89b43942673a1df9b4bd4d66e (2019-06-18 16:00:58 -0400)
blog: improve preview images a bit
> blog: handle different image styles

- blog/index.md
- src/_includes/cta_subscribe_blog_list.html
- src/_includes/preview.html
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/mobile:
c157f6dcb6d12e33309cb70342dedcf4f877af9d (2019-06-19 17:30:23 -0400)
blog: mobile index
> blog: mobile index

- src/_includes/cta_subscribe_blog_desktop.html
- src/_includes/cta_subscribe_blog_list.html
- src/_layouts/blog.html
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/mobile2:
4b7326b81e89588e95b400aa77cce20847f1fc4a (2019-06-20 11:51:29 -0400)
blog: add mobile styles
> blog: add mobile styles

- blog/_config.yml
- docs/_config.yml
- docs/index.md
- src/_config.yml
- src/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/domain:
e70070a5ed6c9958e0c36140ee3aaf7e411c21a7 (2019-06-20 15:42:26 -0400)
update links to blog.tilt.dev
> update links to blog.tilt.dev

- blog/_config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/analytics:
b644fdac5cfe029fdd829d446ff205daa83f6059 (2019-06-20 15:48:02 -0400)
blog: add a new analytics id
> blog: add a new analytics id

- blog/_posts/2019-06-06-observability-doesnt-work-in-dev.md
Hello @nicks,
Please review the following commits I made in branch nicks/correction:
304b1424a99b6c585d2e05a02737c196b413815c (2019-06-20 15:58:28 -0400)
blog: add correction to observability post
> blog: add correction to observability post

- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/about:
db86c76a06fb9924f94dcfddf3fe7d6c83ece47e (2019-06-23 12:45:13 -0400)
about: dynamically count people
> about: dynamically count people

- blog/_posts/2019-01-16-tilt-a-better-ux-for-docker-compose.md
- blog/_posts/2019-04-09-designing-a-better-interface-for-microservices-development.md
- blog/_posts/2019-04-30-tilt-v0-8-release.md
- blog/_posts/2019-05-29-local-development-at-kubecon-eu.md
Hello @nicks,
Please review the following commits I made in branch nicks/links:
c83ad5825a93d8b022a4751fef48fa4352e511d7 (2019-06-23 12:06:39 -0400)
blog: update some canonical links
> blog: update some canonical links

- src/_sass/base.scss
- src/contact.md
leaving the checkboxes for now (pending input from reify), but added some more ways to reach us
> contact: more ways to reach us [ch2796]

- docs/install.md
- docs/upgrade.md
Please review the following commits I made in branch maiamcc/v0.9.3:
e3601e0b14ca6f0112c073c7b610b3b44e895a04 (2019-07-11 17:35:29 -0400)
bump version to v0.9.3
> bump version to v0.9.3

- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/karina:
6d18f1bccec738884389418ad3f33edfa25e556a (2019-07-16 17:32:36 -0400)
remove Karina from about page
> remove Karina from about page

- blog/_config.yml
- docs/_config.yml
- docs/index.md
- src/_config.yml
- src/_data/footer.yml
Hello @nicks,
Please review the following commits I made in branch nicks/twitter:
9eddf79aee7d05fe059fc04bb250a79345f499d0 (2019-07-19 07:06:04 -0400)
update twitter links
> update twitter links

- docs/docker_compose.md
- docs/faq.md
- docs/install.md
- docs/upgrade.md
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/bash:
8355421e6bcfd1d31f897ecc1a560fa2e4242be9 (2019-07-23 17:35:59 -0400)
docs: add user-select:all to code snippets we want people to copy
> docs: add user-select:all to code snippets we want people to copy

- docs/faq.md
ef8a9a2e4073bc336139d6370b91a7f57591ad38 (2019-07-23 17:48:01 -0400)
docs: update the microk8s instructions
> docs: update the microk8s instructions

- docs/tutorial.md
- docs/welcome_to_tilt.md
- src/_data/docs.yml
Hello @yuindustries, @jazzdan,
Please review the following commits I made in branch nicks/guide:
cbe2ca4b087c8a3e413b331a9ad21daf41216d4f (2019-07-25 12:14:21 -0400)
docs: add a lead-in to the Welcome to Tilt guide
> docs: add a lead-in to the Welcome to Tilt guide

- docs/install.md
- docs/upgrade.md
Hello @mariabelenvivanco, @landism,
Please review the following commits I made in branch maiamcc/bump-0.9.6:
bb938acd2eb5a3fbbdc65e6c0a0b758a09f0a803 (2019-07-25 18:04:16 -0400)
bump to 0.9.6
> bump to 0.9.6

- deploy/serve.yaml
- healthcheck.sh
Hello @nicks,
Please review the following commits I made in branch nicks/healthcheck:
17987f4500684827efc6d2958d386571bbee2929 (2019-07-31 13:05:57 -0400)
tweak healthcheck a bit
> tweak healthcheck a bit

- src/product.md
Hello @nicks,
Please review the following commits I made in branch nicks/typo:
a41f1fa5f9185000e2ccf4af25dc87e4a939528a (2019-08-07 14:21:56 -0400)
fix a typo
> fix a typo

- docs/faq.md
- docs/install.md
Please review the following commits I made in branch nicks/install:
893ed362bf689b6c5a105ba77cc065bb2ca137d2 (2019-08-07 17:33:44 -0400)
docs: update the install page to use the installer
> docs: update the install page to use the installer

- Tiltfile
- deploy/api.dockerfile
- src/_data/docs.yml
- src/_includes/api.html
- src/_sass/api.scss
Hello @nicks,
Please review the following commits I made in branch nicks/toc:
21760c0d10d736ad9d98566aca486cdf85e452d4 (2019-08-09 15:47:51 -0400)
api: move functions before classes. Fixes issue #66
> api: move functions before classes. Fixes issue #66

- api/api.py
- src/_includes/api.html
Please review the following commits I made in branch nicks/load:
979a1733786f9e119a0fce4e7fadc200755b6993 (2019-08-09 15:32:27 -0400)
docs: add documentation on include/load
> docs: add documentation on include/load

- src/_includes/functions.html
Hello @nicks,
3884ce0e85285285a9b8db36d95926feec8c8c4d (2019-08-12 12:54:27 -0400)
update api html
> update api html

- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/maria:
ac9d9300d1ef916ecc59e7defffc58ebefe2e9c7 (2019-08-15 16:28:20 -0400)
about: Maria's internship is over :sob:
> about: Maria's internship is over :sob:

- docs/faq.md
- docs/install.md
Hello @nicks,
79015c0a0b2c84212973962e425544affc3f3bbc (2019-08-20 17:07:43 -0400)
docs: as of microk8s v1.15.3, the kubeconfig requires sudo privileges
> docs: as of microk8s v1.15.3, the kubeconfig requires sudo privileges

- docs/choosing_clusters.md
Hello @nicks,
Please review the following commits I made in branch nicks/k3d:
c35fdfd59df8b75633595fac6d842aa3cdfbc600 (2019-08-21 11:46:46 -0400)
docs: more context on k3d and minikube
> docs: more context on k3d and minikube

- blog/_posts/2019-06-27-commit-of-the-month-june.md
- blog/_posts/2019-08-01-commit-of-the-month-july.md
- blog/_posts/2019-08-15-why-does-kubernetes-development-suck.md
081fb7b45dfc3350b91953a30eda5d20b48432e4 (2019-08-21 11:50:25 -0400)
blog: fix image display
> blog: fix image display

- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/maria:
43cc6121a79062a1785cc3c0f856542f2d5e4126 (2019-09-05 18:31:42 -0400)
blog: fix maria's profile
> blog: fix maria's profile

- api/api.py
- src/_includes/functions.html
to reflect https://github.com/windmilleng/tilt/pull/2078
> api docs: update port_forward behavior

- docs/choosing_clusters.md
- docs/faq.md
- docs/install.md
Hello @nicks,
87ecd6acec7551daf96e83e79f05a03ce0721ad0 (2019-09-16 11:20:58 -0400)
add sudo to microk8s commands
> add sudo to microk8s commands

- docs/faq.md
- docs/install.md
Hello @nicks,
Please review the following commits I made in branch nicks/dd:
7c89de18ab609fe774001ca0ecde3fe8095f3f08 (2019-09-16 16:12:57 -0400)
docs: update to use docker-desktop context
> docs: update to use docker-desktop context

- api/api.py
- docs/custom_build.md
- src/_data/docs.yml
- src/_includes/functions.html
Please review the following commits I made in branch nicks/custom:
ff8a0acd50c9e749a2df3595e3de43ae0bd75bd2 (2019-09-20 10:36:29 -0400)
docs: tweak the custom_build docs a bit
> docs: tweak the custom_build docs a bit

- api/api.py
- docs/helm.md
- src/_includes/functions.html
Please review the following commits I made in branch nicks/helm:
86e835daa21861753ada2a134095508a95455e24 (2019-09-20 11:04:19 -0400)
docs: api references for docker_build target and helm options
> docs: api references for docker_build target and helm options

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/release:
a6e88966116feabea815f76e7ac319867283fbf5 (2019-09-20 12:14:43 -0400)
docs: update latest tilt version
> docs: update latest tilt version

- docs/choosing_clusters.md
- docs/faq.md
- docs/install.md
Hello @nicks,
c444d5ad0616d618dd68034885d34bd3258a812e (2019-09-20 14:56:17 -0400)
microk8s: add better error checks to install steps
> microk8s: add better error checks to install steps

- docs/onboarding_checklist.md
Hello @,
Please review the following commits I made in branch maiamcc/onboard-checklist-tilt-up:
242d1fb7929f01fd581f5778bc1bd4a9fdd90a1e (2019-09-24 15:31:19 -0400)
fix some formatting
> fix some formatting

- docs/install.md
- docs/upgrade.md
Please review the following commits I made in branch maiamcc/bump-0.10.9:
5ce0b2a306e1fbe90ce24e83a4ff0eed460c51fc (2019-09-24 16:06:33 -0400)
bump version to 0.10.9
> bump version to 0.10.9

- docs/choosing_clusters.md
Replacing the k3s install URL with the actual k3d install URL :+1: 
Thanks for mentioning k3d and k3s :)
We'll try to make it easier to use for external use :+1:
> correct k3d get url

- blog/_posts/2019-10-16-crash-course-kubernetes-overview.md
Please review the following commits I made in branch nicks/cc:
a00ce5fb00f4141c6463dc1c7448219f4be8939c (2019-10-17 16:03:15 -0400)
add image credit
> add image credit

- api/api.py
- src/_includes/functions.html
Please review the following commits I made in branch nicks/restart-container:
dd6fe31d5369eb55e5a4758309e65c627df15017 (2019-10-22 14:30:46 -0400)
api: more details on restart_container
> api: more details on restart_container

- blog/_config.yml
- docs/_config.yml
- docs/code_of_conduct.md
- docs/faq.md
- src/_config.yml
- src/_layouts/blog.html
- src/contact.md
Hello @nicks,
5be58fc111adf7d59457e7276153ee93af28459e (2019-10-25 11:15:19 -0400)
update email addresses to point at tilt.dev
> update email addresses to point at tilt.dev

- Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/team:
4ee3c726f03e59ec75f47552a698579db876d506 (2019-10-25 11:50:08 -0400)
enable update_history and add a team for tilt.build
> enable update_history and add a team for tilt.build

- api/api.py
- docs/api.md
- src/_includes/functions.html
d6c3fcbd3947f293e2f71e103b08909d230a0b56 (2019-10-25 12:41:34 -0400)
api: make sure all functions link to more thorough reference docs
> api: make sure all functions link to more thorough reference docs

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/job:
02e39ed4ca494be26699179e9f59e01759a0ed2d (2019-10-28 16:51:48 -0400)
docs: update current version to v0.10.15
> docs: update current version to v0.10.15

- blog/_posts/2019-10-28-build-cache-spark-joy.md
Hello @,
Please review the following commits I made in branch maiamcc/disk-space-tweaks:
6d5a541063180a477a40a972497da56c9696fbf2 (2019-10-28 18:01:36 -0400)
blog: tweaks to disk space blog post
> blog: tweaks to disk space blog post

- api/api.py
- docs/faq.md
- src/_includes/functions.html
Hello @nicks,
Please review the following commits I made in branch nicks/faq:
a8336b35a79af908fd8f6aa2a4ab8d738c46319c (2019-10-29 18:35:30 -0400)
docs: clean up the faq and make some links consistent
> docs: clean up the faq and make some links consistent

- docs/product_faq.md
- src/_data/docs.yml
Hello @jazzdan, @dbentley,
Please review the following commits I made in branch nicks/productfaq:
78a5d68dd4b4ebca4489f3a864f8cabf7127248c (2019-10-29 20:56:10 -0400)
docs: Add a product faq
> docs: Add a product faq

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/install:
9aaa3d4ea1a10298269a4360358f8b1878c289fd (2019-11-01 11:49:15 -0400)
docs: update install instructions to 0.10.16
> docs: update install instructions to 0.10.16

- api/api.py
- docs/partner_program.md
- docs/product_faq.md
- src/_data/api_functions.yaml
- src/_includes/functions.html
Hello @dbentley, @landism,
Please review the following commits I made in branch nicks/partner:
e604f806649912eb8202af9ae8629770f5b87db9 (2019-10-30 17:37:14 -0400)
docs: add info on our partner program
> docs: add info on our partner program

- api/api.py
- docs/docker_compose.md
- src/_data/api_functions.yaml
- src/_includes/functions.html
Please review the following commits I made in branch nicks/dc:
462dc2ef78e0b7e6daf6608f292e95b0f18e3941 (2019-11-04 17:16:12 -0500)
api: add docker_compose docs. Fixes https://github.com/windmilleng/tilt/issues/2485
> api: add docker_compose docs. Fixes https://github.com/windmilleng/tilt/issues/2485

- src/_includes/functions.html
When I `tilt up`'d on master it left me with some changes to function.html
> docs: run api doc build

- api/api.py
- docs/helm.md
- src/_includes/functions.html
Please review the following commits I made in branch nicks/helmset:
30f75bc805d3aae5bf5bdcbe67bd788b9e655d95 (2019-11-04 17:04:38 -0500)
docs: helm --set parameter
> docs: helm --set parameter

- src/_includes/job_intro.md
- src/frontend-eng.md
- src/product.md
Please review the following commits I made in branch nicks/job:
8554857daf489f59d2533770607fbad0105be414 (2019-11-01 12:58:47 -0400)
site: post frontend-eng job req
> site: post frontend-eng job req

- src/hello.md
Hello @hyu, @jazzdan,
Please review the following commits I made in branch nicks/kubecon3:
3761da105a3a7bc5b204b781efa6d5a2878679a1 (2019-11-12 16:57:33 -0500)
site: tweak the kubecon landing page a bit based on Mike's suggestions
> site: tweak the kubecon landing page a bit based on Mike's suggestions

- docs/install.md
Hello @nicks,
Please review the following commits I made in branch nicks/link:
f771593a8eee24678ba4fee98fdd6a48e0066820 (2019-11-15 18:25:01 -0500)
docs: update a link to the contributing guide
> docs: update a link to the contributing guide

- src/_includes/header.html
- src/_sass/layout.scss
Hello @hyu,
Please review the following commits I made in branch nicks/banner:
25c9ed6795404734f5cb338749bbd2fc5b384a74 (2019-11-15 16:20:35 -0500)
site: add a kubecon promo banner
> site: add a kubecon promo banner

- docs/local_resource.md
Please review the following commits I made in branch maiamcc/local-resource-blog-link:
4fbab4b97b0399b80bdab41d15414034ccefe9ae (2019-11-15 15:55:55 -0500)
local resource doc: link local resource blog post in local resource doc
> local resource doc: link local resource blog post in local resource doc

- src/_includes/header.html
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/removebanner:
90973d61775e1fda7f26e2064c6bc36e81e8108b (2019-11-22 10:29:51 -0500)
Revert "site: add a kubecon promo banner (#349)"
This reverts commit 6ac1ddf28eba383ecdb27395dc928276a6e62279.
> Revert "site: add a kubecon promo banner (#349)"

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/release:
54a7edc949a6e5e8c8d7c6ccb7e161eede2e4ae7 (2019-11-26 14:29:10 -0500)
docs: update for 0.10.22
> docs: update for 0.10.22

- docs/helm.md
Please review the following commits I made in branch nicks/helmreq:
7e68f84957d56149143a49eb194e5b412df103dd (2019-11-26 12:54:16 -0500)
docs: add notes on helm subcharts
> docs: add notes on helm subcharts

- api/api.py
- docs/custom_build.md
- src/_includes/functions.html
Hello @jazzdan, @maiamcc,
Please review the following commits I made in branch nicks/custombuild:
6e2fd2d04666987d7c4b7f09d7b896934c197ba0 (2019-11-26 15:00:40 -0500)
docs: add details on how to use custom_build with buildah
> docs: add details on how to use custom_build with buildah

- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/l:
1f0de692f7d445ca53ba3ba6c84fac7b0b52dccf (2019-12-10 15:23:23 -0500)
site: update L bio
e2f07f873b78cdcc1d304a8eb4a320a623069022 (2019-12-10 12:07:09 -0500)
site: add L
> site: update L bio

- docs/faq.md
> docs: add note on disable BuildKit in FAQ

- src/_sass/layout.scss
Hello @hyu, @jazzdan,
Please review the following commits I made in branch nicks/header:
14b7ba471df3d83eaf09d04e2f9b6e69503f6985 (2020-01-02 16:00:47 -0500)
blog: cap max-height of feature images
> blog: cap max-height of feature images

- docs/debug_faq.md
- docs/product_faq.md
- docs/snapshots.md
- docs/telemetry_faq.md
- src/_data/docs.yml
- src/_sass/layout.scss
Hello @jazzdan, @l-korbes,
Please review the following commits I made in branch nicks/debug:
45e66fb8fb550aecf3e727989f0c0b9fb70590e9 (2020-01-03 16:46:02 -0500)
docs: add a Tilt debugging guide
> docs: add a Tilt debugging guide

- docs/faq.md
- docs/product_faq.md
- docs/telemetry_faq.md
Hello @nicks,
Please review the following commits I made in branch nicks/hrs:
a171e3fcae314274f4a61fee5b604578ff032a7c (2020-01-07 11:01:29 -0500)
docs: add some dividers to the faqs
> docs: add some dividers to the faqs

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/version:
12550d4ebad92c2902f57cf56c3a5644d0366954 (2020-01-13 19:01:56 -0500)
docs: bump version
> docs: bump version

- api/api.py
- src/_includes/functions.html
This reflects https://github.com/windmilleng/tilt/pull/2808
> tiltfile: document quiet flag for local()

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/bump:
b8b16fc327ed1ba96463e610000633e87523dc79 (2020-01-24 17:56:22 -0500)
bump version to 0.11.3
> bump version to 0.11.3

- src/devtools-eng.md
Please review the following commits I made in branch nicks/jobreq:
c4cee38344b864bab48d6aab2d8efff7ee3c02c5 (2020-01-23 13:27:03 -0500)
job req: devtools engineer
> job req: devtools engineer

- src/devtools-eng.md
Hello @nicks,
Please review the following commits I made in branch nicks/fix:
ae3be0ab7a8b5a4a328183b78e308e35c0b8c80c (2020-01-27 19:26:35 -0500)
site: fix job req metadata
> site: fix job req metadata

- src/about.md
Hello @hyu,
Please review the following commits I made in branch nicks/jobs:
a8b8580c73a9d5d600a809c3436dcfc942432a48 (2020-01-28 11:39:31 -0500)
site: put job listings on the about page
8f9cea251e8cc69e389402b22ecea4a6ab706ccc (2020-01-27 23:07:33 -0500)
site: remove product job posting
> site: put job listings on the about page

- src/_config.yml
- src/_includes/google-analytics.html
Hello @nicks,
Please review the following commits I made in branch nicks/clearbit:
ac575ed17f7ac61e35e5df69e104dd2d5212378b (2020-01-29 16:23:40 -0500)
add clearbit
> add clearbit

- api/api.py
- src/_data/api_functions.yaml
- src/_includes/functions.html
Please review the following commits I made in branch nicks/decodeyaml:
10334b458f91dbc1d723bb18a754ca950af9e81a (2020-02-03 17:21:37 -0500)
api: add decode_yaml
> api: add decode_yaml

- blog/_posts/2017-10-09-12-gothamgo-talks-that-could-have-used-more-glitter.md
- blog/_posts/2018-05-17-how-windmill-prepped-for-gothamgo.md
- blog/_posts/2018-05-22-whats-easier-than-clicking-run-test-not-clicking-it.md
- blog/_posts/2018-06-04-github-propelled-git-to-escape-velocity.md
- blog/_posts/2018-08-28-how-tilt-updates-kubernetes-in-seconds-not-minutes.md
- blog/_posts/2018-12-05-tilt-is-the-start-sh-script-of-my-dreams.md
- blog/_posts/2019-01-16-tilt-a-better-ux-for-docker-compose.md
- blog/_posts/2019-02-07-whats-wrong-with-microservice-dev.md
- blog/_posts/2019-02-21-can-microservices-make-things-simpler.md
- blog/_posts/2019-03-29-microservices-hidden-problem-understanding.md
- blog/_posts/2019-04-09-designing-a-better-interface-for-microservices-development.md
- blog/_posts/2019-04-30-tilt-v0-8-release.md
- blog/_posts/2019-06-19-new-in-tilt-fine-tune-how-your-services-get-updated.md
- blog/_posts/2019-06-21-tilt-v0-9-release.md
Hello @nicks,
Please review the following commits I made in branch nicks/images:
8588b31722d950b54682c6bdd82627985661f29b (2020-02-03 19:23:57 -0500)
blog: fix some image slugs that got lost in the conversion
> blog: fix some image slugs that got lost in the conversion

- src/_includes/head.html
- src/assets/js/intercom.js
Hello @nicks, @hyu,
Please review the following commits I made in branch maiamcc/intercom:
5daa1502b6ab2ba986ebec68aa0163eb1191fc0d (2020-02-04 15:11:00 -0500)
add intercom js to site for chatting with visitors
> add intercom js to site for chatting with visitors

- src/_sass/layout.scss
Hello @nicks,
ffa2cd5e267217e2ad63767f3f3e890863d37904 (2020-02-04 19:42:19 -0500)
blog: adjust tweet layout a bit
> blog: adjust tweet layout a bit

- docs/telemetry_faq.md
Please review the following commits I made in branch nicks/donottrack:
b16d733630412447de8336c5f3e3e24de59cf1f6 (2020-02-04 19:37:07 -0500)
docs: add DO_NOT_TRACK to telemetry FAQ
> docs: add DO_NOT_TRACK to telemetry FAQ

- docs/code_of_conduct.md
- docs/product_faq.md
- src/_includes/footer.html
- src/_includes/job_intro.md
- src/thanks.md
Hello @jazzdan, @hyu,
Please review the following commits I made in branch nicks/company:
a625c0cd4ef8cb3f318e2ef159959317d6e34ce5 (2020-02-06 15:32:06 -0500)
site: remove 'windmill engineering' from the site
> site: remove 'windmill engineering' from the site

- docs/index.md
- docs/telemetry_faq.md
Hello @dbentley, @jazzdan, @maiamcc,
Please review the following commits I made in branch nicks/analytics:
2e906770cd60242e0449858b29e4b690fb691939 (2020-02-06 12:20:29 -0500)
docs: update the docs about analytics changes
> docs: update the docs about analytics changes

- docs/choosing_clusters.md
Please review the following commits I made in branch nicks/kind:
1b3021cd8fb05bd3254e4b627882f78d5c470d88 (2020-02-05 16:20:59 -0500)
docs: Add documentation on Kind local registries
> docs: Add documentation on Kind local registries

- docs/install.md
- docs/upgrade.md
Hello @jazzdan, @nicks,
Please review the following commits I made in branch maiamcc/v0.12.0:
ba3d7c2abc7b2be512f227fa29ddf3234972c546 (2020-02-07 12:14:06 -0500)
bump to v0.12.0
> bump to v0.12.0

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/version:
0d1d5a3423d82b5bd5267435c53f76a46bf155ea (2020-02-12 12:16:03 -0500)
bump to v0.12.1
> bump to v0.12.1

- api/modules/config.py
- docs/tiltfile_config.md
- src/_includes/functions.html
> docs: misc tiltfile config fixes

- api/api.py
- src/_includes/functions.html
Please review the following commits I made in branch nicks/issue2590:
57e5e95d068fbac8068a8947ca57071dc6b5e131 (2020-02-12 15:53:04 -0500)
api: update allow_k8s_contexts doc to reflect what it does in practice. Fixes https://github.com/windmilleng/tilt/issues/2590
> api: update allow_k8s_contexts doc to reflect what it does in practice. Fixes https://github.com/windmilleng/tilt/issues/2590

- src/_includes/head.html
- src/assets/js/intercom.js
Hello @nicks,
Please review the following commits I made in branch maiamcc/rm-intercom:
f11255bfb85c54cd10ffe40621022d17528179b1 (2020-02-13 12:49:12 -0500)
Revert "add intercom js to site for chatting with visitors (#409)"
This reverts commit 713857c3866d13f9659a2f6d3ff8eff3ba0a9aa5.
> remove intercom from the website while we figure out if we want it

- docs/tiltfile_config.md
Please review the following commits I made in branch nicks/down:
8086bca66e8f81cadf4cdb6ea8cad2b92ff6ce02 (2020-02-13 12:33:32 -0500)
docs: clarify that configs work with tilt down
> docs: clarify that configs work with tilt down

- api/api.py
- src/_includes/functions.html
Please review the following commits I made in branch nicks/dockerbuild:
bfddc579daf49e4e695972bbecaf3c54056c66e2 (2020-02-13 12:15:46 -0500)
api: add new docker_build param docs
> api: add new docker_build param docs

- docs/product_faq.md
- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/people:
6d90a32804bf08e5a7435dee67fa7b8bb3d7af43 (2020-02-18 10:56:39 -0500)
src: increment people count
> src: increment people count

- docs/choosing_clusters.md
Hello @nicks, @hyu,
Please review the following commits I made in branch maiamcc/k3d-instructions:
cf9aa7485acccb74a9ef1ef37a74257d074ff707 (2020-02-20 16:51:28 -0500)
link k3d setup in Choosing Clusters doc [ch4461]
> link k3d setup in Choosing Clusters doc [ch4461]

- blog/_posts/2020-02-14-add-your-own-options-to-your-tilt-config.md
- blog/_posts/2020-02-21-add-your-own-options-to-your-tilt-config.md
I'm not super happy with this. I'm open to whatever advice, but particularly looking for help with/assurance it's ok on:
1. the opening sales pitch
2. the way the "let's see what this looks like" is practically documentation
3. image ideas
I was tempted to at least acknowledge (2) with something like "well, this feature is allowing you, as a programmer and Tiltfile-knower, to define an interface that other people use, so we can justify making the explanation a bit complex", but I'm not very convinced by that. Maybe we just don't talk about the Tiltfile contents at all and only describe what it's like as a Tiltfile consumer?
I was tempted to spend an unknown amount of time coming up with an angle I'm happy with, but figured it might be better to get feedback on this as it is.
> blog: tiltfile config

- src/_includes/google-analytics.html
- src/_includes/head.html
- src/_includes/helpful_form.html
- src/_layouts/docs.html
- src/_sass/layout.scss
Hello @jazzdan, @hyu,
Please review the following commits I made in branch nicks/ch1810/helpful:
68d17ceec749591ad26ad479afaa579e398670f0 (2020-02-25 18:37:37 -0500)
docs: add a small feedback form on the docs site
> docs: add a small feedback form on the docs site

- docs/example_csharp.md
- docs/example_go.md
- docs/example_java.md
- docs/example_nodejs.md
- docs/example_python.md
- docs/example_static_html.md
- src/_data/docs.yml
Hello @ellenkorbes, @jazzdan,
Please review the following commits I made in branch nicks/onboarding:
cd502395dd942dbaa49b9ee468a9922628a192da (2020-02-25 16:57:56 -0500)
docs: Add stub docs for languages
> docs: Add stub docs for languages

- docs/tutorial.md
- src/_data/docs.yml
- src/_data/examples.yml
- src/_layouts/docs.html
Hello @jazzdan, @ellenkorbes,
Please review the following commits I made in branch nicks/links:
d5d3da2d97bee02d5908f507aba650058e30c7a9 (2020-02-26 14:37:42 -0500)
docs: plug the examples at the bottom of the tutorial
> docs: plug the examples at the bottom of the tutorial

- src/_includes/job_outro.md
- src/devtools-eng.md
- src/frontend-eng.md
Hello @nicks,
Please review the following commits I made in branch nicks/jobs2:
6b67c97879b1c1c9f623aba65784fb450b67ac9b (2020-02-28 20:13:12 -0500)
site: tweak the jobs page a bit
> site: tweak the jobs page a bit

- docs/tiltfile_concepts.md
> minor typo fixes to tiltfile_concepts doc page

- api/modules/os.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
Hello @landism, @maiamcc,
Please review the following commits I made in branch nicks/osgetcwd:
6af87c4251be456b237a95d254ae526361fa73ed (2020-03-02 13:19:47 -0500)
docs: add docs for os.getcwd()
> docs: add docs for os.getcwd()

- docs/choosing_clusters.md
Hello @nicks,
24b43da0063489a73ab4c6c0956a6055d6062c9d (2020-03-02 23:08:31 -0500)
docs: fix microk8s link
> docs: fix microk8s link

- docs/faq.md
Please review the following commits I made in branch nicks/faq:
39cc1346fcd3afe0dfc9ee02afddd7cc2f58d311 (2020-03-03 12:00:49 -0500)
docs: add an faq item on dynamic configuration
> docs: add an faq item on dynamic configuration

- docs/example_static_html.md
- src/_sass/layout.scss
Hello @nicks,
Please review the following commits I made in branch nicks/shell2:
92924f92219f0e6f67345290c607f7123919c4c6 (2020-03-05 16:49:50 -0500)
docs: fix image captions
> docs: fix image captions

- docs/install.md
- docs/upgrade.md
Hello @nicks, @landism,
Please review the following commits I made in branch maiamcc/bump-0.12.7:
9ff39aa389d3e75808ce57f97a67f75062bc25c2 (2020-03-09 18:12:44 -0400)
bump version to 0.12.7
> bump version to 0.12.7

- docs/example_python.md
- docs/example_static_html.md
Hello @ellenkorbes, @maiamcc,
Please review the following commits I made in branch nicks/ch5311/metrics:
4ceba312d8fe7a5caf66ef83557118e3d279451a (2020-03-12 13:15:57 -0400)
docs: update guides based on discussion in https://github.com/windmilleng/tilt.specs/pull/27
> docs: update guides based on discussion in https://github.com/windmilleng/tilt.specs/pull/27

- docs/using_tilt_extensions.md
Goals of this PR:
- Copyedits and general clarifications.
- Best practice of not changing extensions locally.
- Inform that versioning is not supported.
> Improve using Tilt extensions docs

- docs/custom_build.md
- src/_includes/api/functions.html
Hello @maiamcc, @jazzdan,
Please review the following commits I made in branch nicks/jib:
5e5fb2f63666ad7054806c550783b2e208be42cc (2020-03-17 13:45:09 -0400)
docs: add documentation on how to use Jib with custom_build
> docs: add documentation on how to use Jib with custom_build

- api/api.py
- docs/personal_registry.md
- src/_includes/api/functions.html
Please review the following commits I made in branch maiamcc/host-from-cluster:
651cd0b51ac2731ff9d1aba3cd73cf28e6ba7947 (2020-03-18 12:37:32 -0400)
document default_registry host_from_cluster param [ch5465]
> document default_registry host_from_cluster param [ch5465]

- docs/example_go.md
- docs/example_java.md
- docs/example_python.md
- docs/example_static_html.md
Please review the following commits I made in branch nicks/comments:
f0c2713b09e4670a7fe6ea22ea37f9404b80ab83 (2020-03-18 14:52:39 -0400)
update all the guides in response to comments on https://github.com/windmilleng/tilt.build/pull/473
In the future, when updating shared language,
please update all the guides, not just the one that you're currently writing!
> update all the guides in response to

- src/_includes/api/functions.html
Hello @nicks,
734b8d64344fc41524d545519e274e6ab4c40188 (2020-03-19 17:09:24 -0400)
regenerate api docs
> regenerate api docs

- docs/debuggers_python.md
Please review the following commits I made in branch maiamcc/pdb-tweaks:
1f697430ad21439fab6b03add15a296b6d813ca4 (2020-03-20 16:39:53 -0400)
tweaks to pdb guide
> tweaks to pdb guide

- docs/example_go.md
- docs/example_java.md
- docs/example_python.md
- docs/example_static_html.md
- src/_sass/layout.scss
Hello @nicks, @ellenkorbes,
Please review the following commits I made in branch maiamcc/non-initial-disclaimer:
280091ad47d4ec208576719522254f650d54c325 (2020-03-24 17:35:29 -0400)
add non-initial build disclaimer to all guides
00884077d1e7287f3c82f07364384315000ae594 (2020-03-23 16:12:14 -0400)
wip
> add non-initial build disclaimer to all guides

- docs/example_go.md
- docs/example_java.md
- docs/example_nodejs.md
- docs/example_python.md
- docs/example_static_html.md
Putting in @ellenkorbes 's suggestions from #483
> unify example guide copy with L feedback

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/bump:
bdacd2ac69a0b08f2d4b0c96aeb8bf19167b946c (2020-03-26 20:19:54 -0400)
bump version to 0.12.10
> bump version to 0.12.10

- docs/example_go.md
as requested in [your comment](https://github.com/windmilleng/tilt.build/pull/488#issuecomment-604130586) in #488
> guides: correct snapshot for golang measured

- docs/debuggers_python.md
Not actually convinced we want to take a strong stance on
web-pdb vs remote-pdb, so left this guide referencing remote-pdb
for now, we change it later if people request
> pdb: update links and tidy guide [ch5589]

- docs/example_go.md
- docs/example_java.md
- docs/example_nodejs.md
- docs/example_python.md
- docs/example_static_html.md
- src/_sass/layout.scss
@hyu i didn't get to the accompaning github icon suggestion, but
this seemed like a good start!
> guides: styling to relate own-line links to the line above [ch5388]

- docs/example_python.md
Hello @nicks,
Please review the following commits I made in branch nicks/brokenlink:
b05e59a19bfbb987dee97a48e53e9a4f5570e4b9 (2020-04-03 15:30:48 -0400)
docs: fix an invalid link
> docs: fix an invalid link

- docs/example_nodejs.md
Hello @nicks,
Please review the following commits I made in branch nicks/brokenlink2:
102c25b79bce9902964cfbb3e2de9a8efb9ce66a (2020-04-03 16:15:49 -0400)
docs: fix another broken link
> docs: fix another broken link

- docs/example_csharp.md
- docs/example_go.md
- docs/example_java.md
- docs/example_nodejs.md
- docs/example_python.md
- docs/example_static_html.md
> guides: fix bad link in python guide, unify "recommended setup" links

- docs/file_changes.md
Great docs! Quick typo fix here.
> Fix typo on the "File Changes" page

- src/_includes/api/functions.html
Hello @nicks,
Please review the following commits I made in branch nicks/refresh:
3d9d5fa52c2cfbc58586116d2551e766cbe6f65e (2020-04-09 19:57:54 -0400)
api: rebuild the api html
> api: rebuild the api html

- api/api.py
- src/_includes/api/functions.html
documents https://github.com/windmilleng/tilt/pull/3172
> docs: document version_settings' new constraint param

- blog/_posts/2020-04-16-how-to-not-break-server-startup.md
Hello @nicks,
Please review the following commits I made in branch nicks/ci:
9a6e7f57e45456313845e61791a9deef96d945ea (2020-04-16 15:30:10 -0400)
blog: add a link to the tilt docker repo
> blog: add a link to the tilt docker repo

- src/_config.yml
- src/_includes/google-analytics.html
- src/_includes/google-tag-manager-body.html
- src/_includes/google-tag-manager-head.html
- src/_includes/head.html
- src/_includes/header.html
- src/_includes/helpful_form.html
Hello @nicks,
Please review the following commits I made in branch nicks/optimize:
c04dd1d00dd2fbca375d8e06352611db97e8e07e (2020-04-17 16:53:42 -0400)
install google analytics with gtag.js and use google tag manager
> install google analytics with gtag.js and use google tag manager

- src/_includes/head.html
Hello @nicks,
Please review the following commits I made in branch nicks/optopt:
a935103d499a230ad9b25d1f9afd0f0ff2366682 (2020-04-20 14:57:45 -0400)
move gtag.js to the top
> move gtag.js to the top

- src/_includes/google-analytics.html
Hello @nicks,
Please review the following commits I made in branch nicks/optopt:
a0a6b861a0137675f56cff071b5977c463be1fd9 (2020-04-20 15:19:27 -0400)
Add an anti-flicker snippet to see if that helps with experiment flicker
a935103d499a230ad9b25d1f9afd0f0ff2366682 (2020-04-20 14:57:45 -0400)
move gtag.js to the top
> Add an anti-flicker snippet to see if that helps with experiment flicker

- docs/custom_build.md
- docs/file_changes.md
Please review the following commits I made in branch nicks/custombuild:
a2b8d2b3b876865e80c93d0857c1acb3ba0c3c91 (2020-04-21 13:15:48 -0400)
docs: add more detail on ignore/only for custom_build/local_resource
> docs: add more detail on ignore/only for custom_build/local_resource

- api/modules/os/__init__.py
- src/_data/api/data.yaml
- src/_includes/api/data.html
Please review the following commits I made in branch nicks/osname:
1898e1e47fb17597259895194853049f73ab5f8a (2020-04-21 17:29:18 -0400)
api: document os.name
> api: document os.name

- docs/live_update_reference.md
Hello @maiamcc, @jazzdan,
Please review the following commits I made in branch nicks/liveupdate:
98a02b19118533fbc1f64791bf0181bf0dc79965 (2020-04-27 12:22:06 -0400)
Add example reference to live update reference
> Add example reference to live update reference

- docs/_config.yml
- docs/index.md
- src/_config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/readme:
1ef50803c7d544dcfad4a4cd7eb7beb6845679dd (2020-04-28 10:29:16 -0400)
docs: update index.md for consistency with the github readme
> docs: update index.md for consistency with the github readme

- api/modules/config.py
- docs/tiltfile_config.md
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
whoops never got these into docs
> docs: document config.define_string and define_bool

- blog/_config.yml
- blog/index.md
- docs/partner_program.md
- docs/product_faq.md
- docs/welcome_to_tilt.md
- src/_includes/cta_subscribe_blog_desktop.html
- src/_includes/cta_subscribe_blog_list.html
- src/index.md
- src/subscribe_thanks.md
Hello @nicks,
Please review the following commits I made in branch nicks/multiservice:
cd0cd983f9288c721fd19571dfc77326fd733389 (2020-04-29 10:11:59 -0400)
docs: use multi-service instead of microservice in more places
> docs: use multi-service instead of microservice in more places

- api/modules/os/path.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
Please review the following commits I made in branch nicks/path:
8129c296922f6332b988942cde10652cab67a345 (2020-04-30 15:54:09 -0400)
api: add documentation on new os.path functions
8868b5ad88cf5a5d2b205af40afd6df8a94367f8 (2020-04-30 15:54:09 -0400)
fix
> api: add documentation on new os.path functions

- docs/choosing_clusters.md
Hello @jazzdan, @victorwuky,
Please review the following commits I made in branch nicks/clusters:
a7428b24ce66a47eb675ba08549ce6bd7b2f2bd6 (2020-05-01 15:11:28 -0400)
docs: add documentation on cluster whitelisting and the tilt.dev/registry annotation
> docs: add documentation on cluster whitelisting and the tilt.dev/registry annotation

- docs/choosing_clusters.md
Hello @nicks,
Please review the following commits I made in branch nicks/clusters:
3ff1b20e7ac123f2169dc9e6324e8ed2a1753db3 (2020-05-01 15:30:43 -0400)
docs: fix an escaping issue
> docs: fix an escaping issue

- api/api.py
- docs/choosing_clusters.md
- src/_includes/api/functions.html
Follow up of https://github.com/windmilleng/tilt.build/pull/555/
> docs: Add CRC to docs mentioning which clusters are whitelisted

- Tiltfile
- deploy/base.dockerfile
- deploy/blog.dockerfile
- deploy/docs.dockerfile
- deploy/site.dockerfile
Hello @nicks,
Please review the following commits I made in branch nicks/base:
660f535224b9f3fe89f3a1402d4821ed39034421 (2020-04-30 18:23:49 -0400)
add a base image for the tilt website, and use a real Tilt Cloud team
> add a base image for the tilt website, and use a real Tilt Cloud team

- src/_config.yml
- src/_includes/google-analytics.html
- src/_includes/google-optimize-anti-flicker.html
- src/_includes/head.html
Hello @nicks,
Please review the following commits I made in branch nicks/gtm:
a24097811f2e2227b9d023046d8fffa7118b0f9e (2020-05-04 16:48:59 -0400)
tilt-site: deploy optimize with google tag manager instead of gtag.js
> tilt-site: deploy optimize with google tag manager instead of gtag.js

- src/index.md
Hello @victorwuky, @dbentley,
Please review the following commits I made in branch nicks/new-messaging:
3d88adc2f34d39726bef3db884e1ae3a248b716e (2020-05-04 17:40:19 -0400)
tilt-site: update the homepage with new messaging
> tilt-site: update the homepage with new messaging

- src/_sass/layout.scss
Hello @nicks,
49ab32df990a2501183f5464bc4221427eefd8ea (2020-05-04 18:03:17 -0400)
blog: adjust margin a bit on mobile
> blog: adjust margin a bit on mobile

- src/_data/header.yml
- src/_layouts/enterprise.html
- src/_sass/enterprise.scss
- src/_sass/tilt.scss
- src/assets/svg/enterprise.svg
- src/enterprise.md
I added a link to the top nav, but it's commented-out for now:
In **header.yml**:
```
```
> Add Enterprise page

- api/api.py
- src/_includes/api/functions.html
From https://kubernetes.slack.com/archives/CESBL84MV/p1589296742034600.
> docs: Specify kustomize order

- api/modules/os/__init__.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
Please review the following commits I made in branch nicks/os:
b72dcb44d5b75ff05dec63f93292549510e69124 (2020-05-13 18:18:45 -0400)
api: add docs for os.putenv, os.getenv, os.unsetenv
> api: add docs for os.putenv, os.getenv, os.unsetenv

- api/api.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
docs for [tilt#3313](https://github.com/windmilleng/tilt/pull/3313)
> api: document secret_settings

- api/api.py
- src/_includes/api/functions.html
Hello @jazzdan, @landism,
Please review the following commits I made in branch nicks/bat:
e781a7f71b5723c6a6be8e7e796b41942927a0a2 (2020-05-13 18:28:56 -0400)
api: add docs for batch commands
> api: add docs for batch commands

- docs/install.md
- docs/upgrade.md
Hello @jazzdan, @hyu,
Please review the following commits I made in branch nicks/ch7041/install:
7150d7e04f228044e2e16deb1535eeda0cef6526 (2020-05-19 14:00:21 -0400)
docs: flesh out install/upgrade instructions on windows
> docs: flesh out install/upgrade instructions on windows

- api/api.py
- src/_includes/api/functions.html
this wasn't documented whoooops. Good catch @nicks
> docs: entrypoint can be passed as string or argv

- src/_includes/api/functions.html
Hello @,
Please review the following commits I made in branch maiamcc/make-entrypoint-array-docs:
d811bdd6479f33bf7bf33eecfd4188b9afb5fd53 (2020-05-19 18:01:43 -0400)
api: whoops I forgot to run make api
> api: whoops I forgot to run make api

- src/_layouts/blog.html
Hello @nicks,
Please review the following commits I made in branch nicks/aside:
03d9246f13b67c9acb490080a53cddbd91c238f8 (2020-05-20 11:47:57 -0400)
add some semantic markers to the blog layout
> add some semantic markers to the blog layout

- api/api.py
- src/_includes/api/functions.html
documentation for https://github.com/tilt-dev/tilt/pull/3343
> api ref: document update_settings.k8s_upsert_timeout_secs [ch6947]

- src/_includes/header.html
- src/_layouts/default.html
- src/_sass/header2.scss
- src/_sass/layout.scss
Hello @hyu,
Please review the following commits I made in branch nicks/ch7099:
e5cb8fb8047321ef83313797785c2334bb3284fc (2020-05-26 18:42:57 -0400)
add css class for enabling the header
> add css class for enabling the header

- src/_includes/head.html
- src/_includes/heap-analytics.html
Reverts tilt-dev/tilt.build#559
No longer using Heap
> Revert "Heap Analytics"

- src/index2.md
Hello @hyu,
Please review the following commits I made in branch nicks/ch7188:
9098ddd05ce281aa754c0da62415e4edb77f4505 (2020-05-28 18:59:10 -0400)
site: fix the subscribe form
> site: fix the subscribe form

- src/_sass/home2.scss
- src/assets/js/testimonials.js
- src/index2.md
Hello @hyu,
Please review the following commits I made in branch nicks/ch7183:
a411696ccc7ed39f52eb71afe035ba6c162f7690 (2020-05-28 18:10:16 -0400)
src: make the testimonials list interactive
> src: make the testimonials list interactive

- src/_sass/home2.scss
- src/assets/js/features.js
- src/index2.md
Hello @hyu,
Please review the following commits I made in branch nicks/ch7192:
a984d1710eec2057e31ded18d386a5985f251a95 (2020-05-29 18:07:07 -0400)
site: features list on mobile
> site: features list on mobile

- src/_data/footer.yml
Hello @hyu,
Please review the following commits I made in branch nicks/username:
0aeba3a0143db0ab03166d7f19dad8879a05717c (2020-06-01 15:28:27 -0400)
footer: fix a broken link
> footer: fix a broken link

- src/index2.md
Hello @hyu,
Please review the following commits I made in branch nicks/svg:
93c01299adbb9f13f00425f8967dee0bfadcf492 (2020-06-01 15:26:19 -0400)
site: fix a broken classname
> site: fix a broken classname

- src/_layouts/default.html
Hello @hyu,
Please review the following commits I made in branch nicks/abtest:
9bbf9355eb9b286d0c8119abe0136845ce331f6c (2020-06-01 16:06:39 -0400)
always enable the new header/footer on the new landing page
> always enable the new header/footer on the new landing page

- docs/multiple_repos.md
- src/_data/docs.yml
Helping: https://app.clubhouse.io/windmill/story/4112/a-guide-on-the-tilt-site-on-how-to-structure-large-tiltfiles and https://kubernetes.slack.com/archives/CESBL84MV/p1591008317245700
> Multiple repos

- src/_includes/api/functions.html
- src/_includes/footer2.html
- src/_sass/footer2.scss
Hello @hyu,
Please review the following commits I made in branch nicks/ch7350/footer:
6c6c1a3c5acc6143ea3a0033534188084647363e (2020-06-03 15:28:49 -0400)
footer2: mobile responsive
> footer2: mobile responsive

- stars/inject_stars.sh
also tested this syntax on alpine
> docs: fix stars inject for bsd sed

- docs/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/docsinde:
4da092bd83ac4156ae0ae61c733774a9ce7f40e5 (2020-06-05 17:52:48 -0400)
docs: update the main page with new copy
> docs: update the main page with new copy

- api/api.py
- src/_includes/api/functions.html
Please review the following commits I made in branch maiamcc/decode_json:
36c911ea1801ed1f2a8355704aaf41bd51aee3f1 (2020-06-04 18:30:52 -0400)
api: fix copypasta
> api: fix copypasta

- docs/live_update_reference.md
Hello @,
Please review the following commits I made in branch maiamcc/fix-links:
3d12cac053a9a8214dcc4d53a7993882c52fe8ea (2020-06-08 12:28:28 -0400)
docs: whoops, linked to old repo
> docs: whoops, linked to old repo

- src/_data/footer2.yml
- src/_data/github.yml
- src/_data/header2.yml
- src/_includes/footer2.html
- src/_includes/header2.html
- src/_sass/footer2.scss
- stars/inject_stars.sh
Hello @hyu,
Please review the following commits I made in branch nicks/ch7350/footer:
f6dafc8de95eecf86e7d8d94ac3d389ecc36b1ed (2020-06-03 17:05:16 -0400)
footer2: more mobile responsive
> footer2: more mobile responsive

- docs/live_update_tutorial.md
Hello @nicks, @ellenkorbes,
Please review the following commits I made in branch maiamcc/live-upd-tutorial:
0968b0ce2448477cf1897bb4d234a2968115de05 (2020-06-10 15:40:12 -0400)
docs: redo live update tutorial with restart_process [ch7199]
> docs: redo live update tutorial with restart_process [ch7199]

- docs/local_vs_remote.md
- src/_data/docs.yml
Hello @jazzdan, @victorwuky,
Please review the following commits I made in branch nicks/remote:
444905d2b853729ce3c5357e9774e8ab3d4f69f3 (2020-06-11 14:14:27 -0400)
docs: add a guide for local vs remote clusters
> docs: add a guide for local vs remote clusters

- docs/install.md
- src/_includes/head.html
https://app.clubhouse.io/windmill/story/7269/add-calendly-link-to-install-page
Copied code from https://github.com/tilt-dev/tilt.build/pull/612/files#diff-2abce15a2cf9564d664830a7110820ceL66
> docs: Get help from Dan Miller Calendly on Install page

- src/enterprise.md
This new event type is more easily trackable.
> site: Update Calendly link on Enterprise page

- src/_includes/index_cta.html
Add classes to the CTA buttons so that can create targeted triggers in Google Tag Manager, in order to track clicks for Google Analytics.
> site: CTA button classes for Google Analytics tracking

- api/api.py
- src/_includes/api/functions.html
Please review the following commits I made in branch nicks/ch8057/autoinit:
cf60e83f6a841c524649b32bb9118a680ad248a8 (2020-06-26 18:28:26 -0400)
api: add docs for k8s auto_init
> api: add docs for k8s auto_init

- api/modules/config/__init__.py
- src/_data/api/data.yaml
- src/_includes/api/data.html
> docs: document config.tilt_subcommand

- api/api.py
- src/_includes/api/functions.html
Hello @jazzdan, @landism,
Please review the following commits I made in branch nicks/crd:
ece6d556228e33250ae112ccc82914c5ea16fe25 (2020-07-02 15:33:09 -0400)
api: document image_object parameter
> api: document image_object parameter

- src/_includes/job_outro.md
- src/about.md
- src/product_designer.md
Hello @dbentley, @victorwuky, @hyu,
Please review the following commits I made in branch nicks/product-designer:
1c6f8cbe5616e54af40e99f85f964d8dcb23c65a (2020-07-02 15:57:26 -0400)
site: product designer job posting
> site: product designer job posting

- docs/custom_resource.md
- src/_data/docs.yml
Please review the following commits I made in branch nicks/frameworks:
c70c6e08e7a5982d5e193e72d9a98268bee75e1f (2020-07-02 19:12:06 -0400)
docs: how to configure a custom resource
> docs: how to configure a custom resource

- docs/custom_resource.md
Hello @nicks,
Please review the following commits I made in branch nicks/kibana:
f1b033522b41215257c2ff1548dd4df1280499e3 (2020-07-07 15:00:46 -0400)
docs: add a link to the elasticsearch/kibana example
> docs: add a link to the elasticsearch/kibana example

- docs/custom_resource.md
Hello @nicks,
Please review the following commits I made in branch nicks/airflow:
65b4c28819151a4a6b331627b31df9c11638b743 (2020-07-09 11:53:01 -0400)
docs: add a link to the airflow example
> docs: add a link to the airflow example

- docs/api.md
Hello @nicks,
Please review the following commits I made in branch nicks/secret:
c42388e1aea5066483dd50eca66097bca2e61156 (2020-07-10 15:25:17 -0400)
add secret to list of extensions
> add secret to list of extensions

- src/_includes/job_outro.md
- src/about.md
- src/devtools_eng.md
- src/frontend_eng.md
76192bb2c1cd89dcbc43ff592971f31b8651d909 (2020-07-10 11:04:21 -0400)
site: add a non-active job postings section
> site: add a non-active job postings section

- docs/choosing_clusters.md
Please review the following commits I made in branch nicks/localregistry:
05bf113a8cbcc8bf6a4ace2ac0a3177ea3d9dc0b (2020-07-22 20:36:47 -0400)
docs: add updated documentation on local registries
> docs: add updated documentation on local registries

- docs/upgrade.md
> docs: if a user installed with install script, upgrade with install script

- docs/custom_build.md
- docs/custom_resource.md
Hello @jazzdan, @maiamcc,
Please review the following commits I made in branch nicks/ch8524:
75c9c7baa89fb527a5975232ff52cf29ee5028f3 (2020-07-23 18:37:09 -0400)
docs: more documentation on deploy tags and why we use them
> docs: more documentation on deploy tags and why we use them

- src/_includes/head.html
Hello @hyu,
Please review the following commits I made in branch nicks/ch8502:
d89725a462f6198c2743d8ab9cd3e0f9782b12f1 (2020-07-22 15:34:02 -0400)
site: update fonts to use corp typekit account
adds family:upgrade, weight:600
> site: update fonts to use corp typekit account

- src/_data/github.yml
- src/_includes/index_cta.html
- src/_layouts/default.html
- src/_sass/enterprise.scss
- src/_sass/home.scss
- src/_sass/tilt.scss
- src/_sass/tilt2.scss
- src/assets/js/cta.js
- src/index.md
Notes:
* The buttons are now slightly askew in the call to action. Paging @hyu for help :
* The close button should probably be styled better. Any ideas?
* The calendly widget isn't exactly centered inside the modal. Any ideas? Maybe it should be flexbox inside the modal?
* Any ideas for better copy?
> make a schedule a demo modal popup

- docs/faq.md
Hello @maiamcc, @victorwuky,
Please review the following commits I made in branch nicks/clusterdetection:
c5c303776f1cd51ca1d2f35b428a8f5e591a6757 (2020-07-30 17:26:50 -0400)
docs: add notes on cluster detection
> docs: add notes on cluster detection

- src/_includes/job_outro.md
Hello @nicks,
Please review the following commits I made in branch nicks/resume:
ecf95d9c2fd97cdde36b7813217d36b9964c2f20 (2020-08-03 12:28:31 -0400)
site: add a note about attaching a resume
> site: add a note about attaching a resume

- src/_includes/job_intro.md
Hello @nicks,
Please review the following commits I made in branch nicks/job:
5017a069ce9e992844510993e6e191dcf6e531f4 (2020-08-03 17:51:57 -0400)
tweak the job intro a bit
> tweak the job intro a bit

- docs/index.md
- docs/install.md
- docs/upgrade.md
Hello @victorwuky, @maiamcc,
Please review the following commits I made in branch nicks/conda:
97fc36c3a17229bae47e6b495c8c1eeebd5d5cd0 (2020-08-03 13:58:33 -0400)
docs: add conda-forge installer
https://github.com/conda-forge/tilt-feedstock
> docs: add conda-forge installer

- src/_includes/index_cta.html
- src/_sass/home.scss
- src/_sass/tilt.scss
- src/_sass/tilt2.scss
- src/assets/js/cta.js
Still needs a bit of styling love, paging @hyu :) but it works!
> src: make callback option in modal

- api/api.py
- src/_includes/api/functions.html
Hello @nicks,
Please review the following commits I made in branch nicks/duplicates:
659df5e33679bea8fd0eb908bc885d48275745b9 (2020-08-10 16:25:21 -0400)
docs: add api docs on allow_duplicates()
> docs: add api docs on allow_duplicates()

- docs/integrating_bazel_with_tilt.md
Hello @nicks,
Please review the following commits I made in branch nicks/bazel:
7ae102a43e21f79c251167bdfe9d11e860664095 (2020-08-11 18:02:25 -0400)
seo description on the bazel guide
659df5e33679bea8fd0eb908bc885d48275745b9 (2020-08-10 16:25:21 -0400)
docs: add api docs on allow_duplicates()
> seo description on the bazel guide

- docs/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/asdf:
19ac8d0d12f1ad67625e245d7525eb203ed3c49b (2020-08-11 18:46:03 -0400)
add a reference to asdf on the index page
> add a reference to asdf on the index page

- api/api.py
- deploy/api.dockerfile
- docs/personal_registry.md
- src/_data/api/data.yaml
- src/_includes/api/data.html
- src/_includes/api/functions.html
Hello @nicks,
7273b05f5d7485bf247452c712c4ef3b570e36cf (2020-08-14 19:52:59 -0400)
add api docs for v0.17.2 primitives
> add api docs for v0.17.2 primitives

- docs/local_resource.md
Please review the following commits I made in branch nicks/localresource:
22b2b868ed554215d144bd6c8884acb7d45d95f9 (2020-08-14 20:03:41 -0400)
docs: add detail on dependencies and parallelism to local_resource docs
> docs: add detail on dependencies and parallelism to local_resource docs

- docs/custom_resource.md
Hello @nicks,
Please review the following commits I made in branch nicks/prometheus:
5143c003361129a1696db8de78a5d6d4ce07772a (2020-08-26 17:01:35 -0400)
docs: add a note on the prometheus example
> docs: add a note on the prometheus example

- api/index.rst
- api/modules/shlex/__init__.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
> docs: document shlex.quote

- docs/index.md
- src/_data/github.yml-e
- src/_sass/docs.scss
- src/_sass/tilt.scss
Let's use L's new video in the Docs, just like we do on the home page. Aka: Deprecate that old video I made where I talk about the TUI! 😬
> Docs: update Tilt in Two Minutes

- src/about.md
Hello @nicks,
1eecdabb642adfea46d0f70206ae6b8d58127bb6 (2020-09-10 14:30:24 -0400)
fix an unclosed tag
3ffc830d257bb96d2b0e5475cc1207aa8c3ae1c7 (2020-09-08 12:33:44 -0400)
take down product designer job posting
> fix an unclosed tag

- src/_includes/job_outro.md
- src/about.md
- src/devtools_eng.md
- src/frontend_eng.md
Please review the following commits I made in branch nicks/eng:
0e2c7f0e78ee1cdb7996588078229a59b6376d07 (2020-09-10 14:55:57 -0400)
re-open job reqs for frontend and devtools engineer. Makes them more senior and adds some resposibilities
> re-open job reqs for frontend and devtools engineer. Makes them more senior and adds some resposibilities

- docs/example_nodejs.md
Hello @nicks,
Please review the following commits I made in branch nicks/jsdebugger:
6c2804e69b1fe2e7d6acb7494f47234be1c32b83 (2020-09-14 12:30:20 -0400)
add a link to the js debugger example
> add a link to the js debugger example

- src/_sass/home.scss
From: https://github.com/tilt-dev/tilt/issues/3778
| Existing | New |
| --- | --- |
|  ![existing](https://user-images.githubusercontent.com/10860550/93224375-08bfa880-f73f-11ea-88c5-82358c917a91.gif) | ![new](https://user-images.githubusercontent.com/10860550/93224405-107f4d00-f73f-11ea-867e-9712cf56f0e6.gif) |
> landing: Fix padding so can easily read to end of scrolling section

- Tiltfile
- docs/debug_faq.md
- src/_data/github.yml
Hello @victorwuky,
Please review the following commits I made in branch nicks/metrics:
b14d55b1996c319e46005a5ad4c10cf58f76396e (2020-09-16 14:25:57 -0400)
add docs on experimental_metrics_settings
> add docs on experimental_metrics_settings

- docs/install.md
- docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/homebrew:
093975c4faaba6f15d321d564cfaab54d32eccdd (2020-09-16 18:29:14 -0400)
add a note that the installer now uses homebrew on linux
> add a note that the installer now uses homebrew on linux

- docs/custom_build.md
Hello @nicks,
Please review the following commits I made in branch nicks/custombuild:
77f924c53eac795e519497cd9803f787e621a9d5 (2020-09-18 20:04:27 -0400)
add a note on REGISTRY_HOST to the custom_build guide
> add a note on REGISTRY_HOST to the custom_build guide

- src/index.md
Hello @hyu,
Wanted to link someone directly to our Testimonials so tossed in a
header ID -- this okay?
> docs: add anchor to testimonials on homepage

- docs/choosing_clusters.md
Hello @maiamcc, @ellenkorbes,
Please review the following commits I made in branch nicks/minikube:
de2811cd344deea206dab4954d306bbc025cbbdf (2020-09-22 15:36:07 -0400)
docs: link to our registry guide in the minikube docs
> docs: link to our registry guide in the minikube docs

- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/dmiller:
0a3cbe6085cbd485977cdd0861146c88b64f3689 (2020-09-26 17:55:02 -0400)
remove dmiller. Good luck Dan!
> remove dmiller. Good luck Dan!

- api/modules/config/__init__.py
- src/_data/api/data.yaml
- src/_includes/api/data.html
Please review the following commits I made in branch nicks/main:
aed0a59bea02ec89e9d6d58afb0e194a2e0697fe (2020-09-29 12:46:00 -0400)
docs: add docs on main_dir, main_path
> docs: add docs on main_dir, main_path

- api/api.py
- docs/file_changes.md
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
Please review the following commits I made in branch nicks/watch:
aa0b6928cd75b06ae551382dda3759bed1806857 (2020-09-29 13:02:19 -0400)
add docs on watch_settings
> add docs on watch_settings

- api/api.py
- src/_includes/api/functions.html
Hello @nicks,
Please review the following commits I made in branch nicks/issue767:
7c21e2e7f812e6c2a3ae25f44b840c587c9654c4 (2020-10-16 10:34:01 -0400)
update version_settings examples. Fixes https://github.com/tilt-dev/tilt.build/issues/767
> update version_settings examples. Fixes https://github.com/tilt-dev/tilt.build/issues/767

- api/api.py
- src/_includes/api/functions.html
Hello @nicks, @landism,
Please review the following commits I made in branch maiamcc/more-endpoint-docs:
6853cfa631f4245669a6c0c18502e10cf256b313 (2020-10-19 12:31:38 -0400)
api: document port_forward.link_path, k8s_resource.links
> api: document port_forward.link_path, k8s_resource.links

- docs/integrating_bazel_with_tilt.md
Hello @landism, @maiamcc,
Please review the following commits I made in branch nicks/bazel:
26ba429493913694eb5d9960ad374452dbe07db0 (2020-10-28 17:14:47 -0400)
docs: fix some bugs in the bazel guide
> docs: fix some bugs in the bazel guide

- api/api.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
Please review the following commits I made in branch nicks/load-dynamically:
24fb78ca0505acaa02a9d4af7085e8b490c1b389 (2020-10-28 17:57:00 -0400)
docs: add api docs for load_dynamic
> docs: add api docs for load_dynamic

- src/_includes/index_cta.html
- src/enterprise.md
This new event includes both Dan and Peter, per [this story](https://app.clubhouse.io/windmill/story/10059/add-peter-to-enterprise-demo)
> Update calendly demo

- docs/example_bazel.md
- docs/integrating_bazel_with_tilt.md
- src/_data/examples.yml
Hello @maiamcc, @victorwuky,
Please review the following commits I made in branch nicks/bazel:
0cbff4a823754b0c1363f9fb79fa5ae8e72b1d54 (2020-11-05 10:59:06 -0500)
docs: add more Bazel docs, including how to do live-update
> docs: add more Bazel docs, including how to do live-update

- api/api.py
- src/_includes/api/functions.html
Hello @nicks,
Please review the following commits I made in branch maiamcc/port-forward-host:
480dfbe45808aa3607911ae5fb3d2d2ec3025c6e (2020-12-07 15:57:37 -0500)
api: port_forward.host docs
> api: port_forward.host docs

- src/about.md
Turns out I can spell Sriracha but not enthusiast 🤦
> site: fix typo in about page bio

- api/api.py
- api/modules/os/path.py
- src/_includes/api/functions.html
Please review the following commits I made in branch nicks/os.path.exists:
5a6c38686fa5ce5a479f224270ff5e1ba0753f93 (2021-01-14 11:18:35 -0500)
api: docs for tilt 0.18.4 (os.path.exists, command_bat)
> api: docs for tilt 0.18.4 (os.path.exists, command_bat)

- src/about.md
62dac0281848d9b3d1d87570729b094589f6b803 (2021-01-15 09:47:31 -0500)
site: update job postings to clarify that we're focused on frontend engineers
> site: update job postings to clarify that we're focused on frontend engineers

- docs/choosing_clusters.md
Please review the following commits I made in branch nicks/k3d:
8b2df93c0863656079e4384cb6c6c702dc133d0f (2021-01-29 13:27:46 -0500)
docs: update tilt docs on k3d
> docs: update tilt docs on k3d

- api/api.py
- docs/local_resource.md
- docs/resource_dependencies.md
- src/_includes/api/functions.html
* Success criteria for each probe type
* Update resource dependencies to mention readiness probes
> docs: clarify some details for readiness probes

- docs/live_update_reference.md
> docs: add CRDs to the list of live_update exceptions

- src/_includes/job_outro.md
https://app.clubhouse.io/windmill/epic/11234
> tilt-site: Update contact us link in job outro to an email link

- api/api.py
- src/_includes/api/functions.html
Please review the following commits I made in branch nicks/dclinks:
bc396fbc69a7951fd0741c0c301f6cfbc3e621da (2021-02-12 19:28:33 -0500)
api: add dc_resource(links)
> api: add dc_resource(links)

- docs/tutorial.md
The tutorial missed a step mentioning to open the UI
> Update tutorial to add missing step

- docs/custom_build.md
- docs/local_vs_remote.md
Hello @ellenkorbes, @landism,
Please review the following commits I made in branch nicks/remote:
ab01d3b320b4ed7c6e9c658332f68e8cc16430e0 (2021-02-18 15:17:55 -0500)
docs: add more cross-references about custom_build
> docs: add more cross-references about custom_build

- api/api.py
- docs/choosing_clusters.md
- src/_includes/api/functions.html
Hello @landism, @maiamcc,
Please review the following commits I made in branch nicks/allow-context:
f5082d31db8ca1614bb151c4b09e0e2f4b911c7a (2021-02-18 13:09:43 -0500)
docs: explain allow_k8s_context(k8s_context()) pattern
> docs: explain allow_k8s_context(k8s_context()) pattern

- api/modules/os/path.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
docs for https://github.com/tilt-dev/tilt/pull/4207
words are hard -- especially having a hard time explaining the args. halp?
> docs: api docs for os.path.relpath

- docs/product_faq.md
- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/victor:
a226919e866fc3f7b16fdd5a9216a552025b2511 (2021-03-07 17:08:17 -0500)
site: remove victor from site
> site: remove victor from site

- docs/contribute_extension.md
- src/_data/github.yml
to match https://github.com/tilt-dev/tilt-extensions/pull/143
> docs: fix api server log extension example

- blog/_posts/2021-03-18-kubernetes-is-so-simple.md
Hello @nicks,
Please review the following commits I made in branch nicks/edits:
52ef267fffbbd4e63d851c99cf9f7c734bdb57d5 (2021-03-18 17:41:35 -0400)
simple pronoun edits
> simple pronoun edits

- docs/example_bazel.md
- docs/example_csharp.md
- docs/example_go.md
- docs/example_java.md
- docs/example_nodejs.md
- docs/example_python.md
- docs/example_static_html.md
Please review the following commits I made in branch nicks/ci:
5024665f1fd5c55c6f62f7f47a0a95d28fe4242b (2021-03-22 13:45:07 -0400)
docs: add notes to the example on CI
> docs: add notes to the example on CI

- docs/helm.md
Please review the following commits I made in branch nicks/helm:
ba62c7d7c9194b0732f2e90042d311afbb9476b1 (2021-04-13 10:10:07 -0400)
docs: add more detail on how to use helm_remote
> docs: add more detail on how to use helm_remote

- src/about.md
- src/advocate.md
Hello @ellenkorbes, @dbentley,
Please review the following commits I made in branch nicks/devrel:
4303709e30e851e338a998c3d5d1753f7514142e (2021-04-15 14:38:31 -0400)
site: add devrel job posting
> site: add devrel job posting

- api/index.rst
- api/modules/sys/__init__.py
- src/_data/api/data.yaml
- src/_includes/api/data.html
Hello @milas, @landism,
Please review the following commits I made in branch nicks/sys:
4a878e36f493a10432698104c78872c1acd0123f (2021-04-19 13:31:09 -0400)
api: add sys.argv, sys.executable to api docs
> api: add sys.argv, sys.executable to api docs

- src/_layouts/docs.html
- src/_layouts/rollout.html
Hello @nicks,
Please review the following commits I made in branch nicks/search:
7323f87ae3cd592be736778d64a63237aff08ea3 (2021-04-19 19:04:28 -0400)
fix a bug when searching from a subdir
83a945e48797549e40839d0f5f868e32c2ed1ab6 (2021-04-19 18:01:36 -0400)
Gemfile: update deps, add Tiltfile script for updating Ruby deps in the container
> fix a bug when searching from a subdir

- docs/upgrade.md
> Fixed typo

- blog/_posts/2021-05-18-entr-the-dragon.md
Hello @nicks,
Please review the following commits I made in branch nicks/entr:
7f43622cd3db1fa77638d0ef4c35d0eb6c87e6d3 (2021-05-18 12:43:17 -0400)
blog: fix a bad slug
78c530c6a47e19a92b28ac5a2c9cc29488bd2c4b (2021-05-18 11:53:06 -0400)
entr: a blog post
> blog: fix a bad slug

- src/_includes/index_cta.html
Hello @nicks,
Please review the following commits I made in branch nicks/typoe:
dacc07a556265a2a764f5166422f0b134537ea9f (2021-05-18 12:44:23 -0400)
site: update a calendly link
> site: update a calendly link

- docs/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/readme:
193ec45cabb0aafc35714b57a92016d617c670cd (2021-06-08 18:34:12 -0400)
docs: duplicate updates to github readme'
> docs: duplicate updates to github readme'

- docs/file_changes.md
Hello @milas,
Please review the following commits I made in branch nicks/filewatch:
83340756d97c9f091c784d3467e3ea9491bba0c3 (2021-06-10 12:40:59 -0400)
docs: cannibalize the FileWatch API blog post for docs
> docs: cannibalize the FileWatch API blog post for docs

- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/maia:
7a15120c4a8457a7f869f97e16005b24f6858264 (2021-06-14 10:43:34 -0400)
about: remove maia
> about: remove maia

- src/index.md
Hello @hyu, @ellenkorbes,
Please review the following commits I made in branch nicks/messaging:
1277bf311e889941e4f7ea9639c870a2cb698999 (2021-06-14 10:58:51 -0400)
site: update headline with new messaging
> site: update headline with new messaging

- api/api.py
- src/_includes/api/functions.html
Accompanying [tilt/#4644](https://github.com/tilt-dev/tilt/pull/4644/files), following [tilt/#4549](https://github.com/tilt-dev/tilt/issues/4549).
> add command working directory for local/local_resource

- blog/_posts/2021-06-21-uibutton.md
(Went to close VS Code and realized I hadn't saved this 🤦)
> blog: add image attribution for UIButton post

- docs/cli/tilt_up.md
Accompanies [tilt#4668](https://github.com/tilt-dev/tilt/pull/4668).
> docs: add namespace flag information for tilt up cli

- src/about.md
Hello @nicks,
2b9000983a3d0cd72aaff4f6b7ccac9ae26b64b0 (2021-06-30 12:10:09 -0400)
site: update hiring
> site: update hiring

- src/_includes/cta_subscribe_blog_desktop.html
- src/_includes/cta_subscribe_blog_list.html
- src/enterprise.md
- src/index.md
- src/liftoff.md
Hello @hyu,
Please review the following commits I made in branch nicks/mailchimp:
20730ce47a28e86ba0bbedb0f323fc0fa5cb1f51 (2021-06-29 14:50:02 -0400)
site: convert all subscribe forms to mailchimp
> site: convert all subscribe forms to mailchimp

- src/_sass/layout.scss
- src/subscribe.md
Hello @hyu, @ellenkorbes,
Please review the following commits I made in branch nicks/subscribe:
57e54ead1ec04df5e9b6e97ddb346182dc32d0a7 (2021-06-29 15:20:43 -0400)
add a standalone subscribe page
20730ce47a28e86ba0bbedb0f323fc0fa5cb1f51 (2021-06-29 14:50:02 -0400)
site: convert all subscribe forms to mailchimp
> add a standalone subscribe page

- docs/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/newsletter:
ba295b5dcd2f5171918214bf43d07b4f29f70a7e (2021-07-01 11:56:05 -0400)
tease the newsletter on the docs site
> tease the newsletter on the docs site

- src/_redirects
Hello @ellenkorbes,
Please review the following commits I made in branch nicks/onlydevs:
8b3cd9409387bc9175535860168c0dbb139f91af (2021-07-26 10:42:09 -0400)
site: add a redirect to the vscode extension
> site: add a redirect to the vscode extension

- docs/index.md
- src/_includes/index_cta.html
Hello @milas, @peterchapman,
Please review the following commits I made in branch nicks/zoom:
89a5fcf5b2b490e7f8d6fcc334339e7f7239e023 (2021-07-29 11:22:51 -0400)
site: update office hours link
8b3cd9409387bc9175535860168c0dbb139f91af (2021-07-26 10:42:09 -0400)
site: add a redirect to the vscode extension
> site: update office hours link

- api/api.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
See tilt-dev/tilt#4819 for feature implementation.
> api: add `exit()` for early return from Tiltfile

- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/lucie:
a4c737f174a2d2f78bc5fabb6591d83e02204855 (2021-08-16 10:22:11 -0400)
site: remove Lucie. end of a successful internship!
> site: remove Lucie. end of a successful internship!

- api/index.rst
- api/modules/v1alpha1/__init__.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
Hello @milas, @landism,
f3ab0c72597c18e92dfe1a87c4170b1f4892e72e (2021-08-13 14:51:21 -0400)
api: add extension_repo, extension
Eventually we want this part of the API to be autogenerated from
data models. This is just manually bootstrapping the process.
The comments are all copied-and-pasted from the data model comments.
> api: add extension_repo, extension

- deploy/api.dockerfile
- src/_includes/cta_docs.html
Hello @nicks,
Please review the following commits I made in branch nicks/typo:
d58b047fbfe330bd2ee45fceb1ce501cef278e54 (2021-08-17 14:26:39 -0400)
site: minor bug fixes
- upgrade nodejs code generator
- hairsp entity is getting escaped somewhere; just use a different entity
> site: minor bug fixes

- docs/search.html
> docs: open search results in same window

- api/api.py
- src/_includes/api/functions.html
Hello @milas, @landism,
Please review the following commits I made in branch nicks/discoverystrategy:
d539209cc3cdf8e28e13f931cb7784084c5026e5 (2021-08-27 17:15:04 -0400)
docs: add discovery_strategy
> docs: add discovery_strategy

- src/_includes/index_cta.html
- src/enterprise.md
- src/liftoff.md
- src/user-research.md
Hello @hyu, @milas,
Please review the following commits I made in branch nicks/calendly:
6355924fc1b1975d263fbd7b0c4a4d2194203979 (2021-08-30 13:58:11 -0400)
site: update calendly links
> site: update calendly links

- blog/_posts/2021-09-09-kubefwd-operator.md
Hello @nicks,
Please review the following commits I made in branch nicks/typo2:
244d6fec944127c0acba5efe0bfff996c5c6c822 (2021-09-09 21:50:40 -0400)
blog: fix a typo
> blog: fix a typo

- blog/_posts/2021-09-09-kubefwd-operator.md
Hello @nicks,
Please review the following commits I made in branch nicks/typo2:
47b756837a7158d6d34cd5b942f4d8d324edde68 (2021-09-10 10:24:13 -0400)
adjust formatting
244d6fec944127c0acba5efe0bfff996c5c6c822 (2021-09-09 21:50:40 -0400)
blog: fix a typo
> adjust formatting

- api/api.py
- src/_includes/api/functions.html
See tilt-dev/tilt#4934 for implementation.
> api: add `platform` arg to `docker_build`

- docs/contribute_extension.md
Noticed a couple people ping Victor directly on PRs last week, which was suspicious - turns out we were telling folks to do that 🙃
> docs: update extension review process

- blog/_posts/2021-09-21-ngrok-operator.md
- src/_data/github.yml
Hello @nicks,
Please review the following commits I made in branch nicks/ngrok:
6da61f2fe5e11b80dadf4ce67bc1602d4b996ca3 (2021-09-21 15:27:42 -0400)
blog: formatting fix
> blog: formatting fix

- src/_data/people.yml
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/peter:
eadc25369f589922755ff51624a59aead0aeae16 (2021-09-28 10:16:14 -0400)
site: remove Peter
> site: remove Peter

- src/_includes/job_intro.md
- src/_includes/job_outro.md
- src/about.md
- src/operations_manager.md
Hello @nicks,
Please review the following commits I made in branch nicks/jobreq:
89eedd4fc90b25fc0709a9d981b59a957fff91cd (2021-10-21 16:04:45 -0400)
site: operations manager job req
> site: operations manager job req

- blog/_posts/2021-10-25-tilt-news-october-2021.md
- blog/_redirects
Hello @chimney42,
Please review the following commits I made in branch nicks/slug:
93c6747e6a61e15fe20ed6161d3922bfcd75d5bf (2021-11-04 15:35:18 -0400)
blog: fix the october news url
> blog: fix the october news url

- src/_includes/index_cta.html
- src/_sass/enterprise.scss
- src/_sass/home.scss
- src/assets/js/cta.js
Hello @hyu,
Please review the following commits I made in branch nicks/display:
ccb983b106413b8684a37c57dbcf1118db2b3e0a (2021-11-05 18:59:53 -0400)
site: fix scrolling on ios safari
this revealed a bunch of larger a11y issues with the modal,
which i fixed as well
fixes https://github.com/tilt-dev/tilt.build/issues/970
> site: fix scrolling on ios safari

- docs/personal_registry.md
- src/_data/docs.yml
Hello @chimney42, @milas, @hyu,
Please review the following commits I made in branch nicks/registry:
96c8bcb6997c787205556a76626a90fc0423c57f (2021-11-09 16:45:26 -0500)
docs: rewrite the guide to registries
> docs: rewrite the guide to registries

- blog/_posts/2021-11-04-docker-build-alternatives.md
Hello @nicks,
Please review the following commits I made in branch nicks/ko:
47948a528d02d3c2152253d9be9c4a21e31ff7be (2021-11-12 14:30:34 -0500)
blog: add notes on kodata
> blog: add notes on kodata

- docs/example_go.md
- docs/example_nodejs.md
- docs/example_python.md
Hello @milas, @chimney42,
Please review the following commits I made in branch nicks/examples:
902b111c8aae27ac7077da6ccb0c4f08d77506f8 (2021-11-12 14:58:35 -0500)
docs: add pixeltilt and tilt-avatars links
> docs: add pixeltilt and tilt-avatars links

- api/api.py
- src/_data/api/functions.yaml
- src/_includes/api/functions.html
See tilt-dev/tilt#5136 and tilt-dev/tilt#5155 for implementation
in Tilt.
> docs: add `k8s_custom_deploy` API reference

- src/_sass/blog.scss
Hello @hyu,
Please review the following commits I made in branch nicks/fontsize:
443b5a9be5df2d270b6248965d4c7eebadbd8466 (2021-11-16 18:23:23 -0500)
blog: use line-clamp for better description clipping
> blog: use line-clamp for better description clipping

- api/api.py
- src/_includes/api/functions.html
Relates https://github.com/tilt-dev/tilt/issues/5196
> docs: docker_build+Docker Compose caveat

- blog/_config.yml
- docs/custom_resource.md
Hello @chimney42, @milas,
Please review the following commits I made in branch nicks/knative:
3bd52d6992a208ac036603de0c8ba341f39b31ae (2021-11-23 11:07:53 -0500)
docs: add knative to the CRD guide
> docs: add knative to the CRD guide

- api/api.py
- docs/manual_update_control.md
- src/_data/github.yml
- src/_includes/api/functions.html
To be merged when tilt-dev/tilt#5225 is released.
- Update dc_resource docs to include auto_init
- Updated stars
> Add dc_resource/auto_init docs

- docs/docker_compose.md
- docs/local_resource.md
- src/_data/docs.yml
- src/_includes/api/functions.html
Hello @chimney42, @nicksieger,
Please review the following commits I made in branch nicks/dc:
b9ed488ec549640f39fec342c65c655971c3eb01 (2021-12-06 13:58:43 -0500)
docs: rewrite docker-compose docs and add notes on auto_init
> docs: rewrite docker-compose docs and add notes on auto_init

- Makefile
- hack/gen_cli_toc_helper.py
- hack/inject_cli_toc.sh
- src/_data/docs.yml
- src/_includes/api/functions.html
Hello @nicks,
Please review the following commits I made in branch nicks/hack:
df2c0366b6550b80cc5a25aca2c00c570396d578 (2021-12-10 17:33:01 -0500)
autogenerate cli toc
> autogenerate cli toc

- src/_sass/docs.scss
Hello @nicks,
Please review the following commits I made in branch nicks/accordian:
6dadc5ba4607a71bef844ee7a1f92cd2c5b2f67b (2021-12-10 18:09:10 -0500)
docs: increase the max size of the accordion
> docs: increase the max size of the accordion

- src/_data/github.yml-e
- src/_data/people.yml
- src/_includes/footer.html
- src/about.md
Hello @nicks,
Please review the following commits I made in branch nicks/l:
7b9f4b50e672bc854c34daf04eceb8ea6be1a569 (2021-12-13 14:51:17 -0500)
site: remove L :sob:
> site: remove L :sob:

- docs/index.md
- docs/tiltfile_authoring.md
- docs/tutorial/index.md
- src/_data/docs.yml
Please review the following changes for the Tiltfile Tutorials:
- Change the title and sidebar content for Tutorial (aka new tutorial)
- Change the title and sidebar content for Tiltfile Guide (aka old tutorial)
> docs: Improve sidebar content for Tutorials

- hack/gen_cli_toc_helper.py
- hack/inject_cli_toc.sh
- src/_data/docs.yml
Hello @nicks,
Please review the following commits I made in branch nicks/cli2:
8ba03062616d564b9fe001e5640b71e2b78b31f3 (2021-12-17 16:30:52 -0500)
docs: fix toc
> docs: fix toc

- api/api.py
- docs/docker_compose.md
- src/_includes/api/functions.html
To be merged with 0.23.4 release
> docs: update for `docker_compose(Blob)`

- api/api.py
- src/_includes/api/functions.html
Hello @milas,
Please review the following commits I made in branch nicks/imagedeps:
09168cc67d856d8748f86c3d30149ece36e651c4 (2021-12-17 19:00:04 -0500)
api: add image_deps to k8s_custom_deploy
> api: add image_deps to k8s_custom_deploy

- api/api.py
- src/_includes/api/functions.html
Hello @landism, @milas,
Please review the following commits I made in branch nicks/custombuild:
6259f3fff1f78484e786a0676a880bc707f9e91a (2022-01-03 16:20:29 -0500)
api: update custom_build api docs
> api: update custom_build api docs

- Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/templating:
580a816a853f875c652db3585b391f5b52d4a6a0 (2022-01-10 18:50:27 -0500)
tiltfile: turn on disable resources feature
> tiltfile: turn on disable resources feature

- docs/choosing_clusters.md
Hi @nicks @milas 
could you please review this PR which adds a section about Rancher Desktop in our "Choosing a Local Dev Cluster" guide.
Also, I don't know enough about Rancher Desktop to provide a list of Pros and Cons, so I'd appreciate your input here 🙏 
Thanks!
> docs: add Rancher Desktop section on choosing clusters guide

- docs/api.md
- src/_data/github.yml
Hi @milas 
- adds a new entry for color extension to docs
> docs: adds entry to docs for color extension

- docs/helm.md
- docs/templating.md
- src/_data/docs.yml
Hello @lianmakesthings, @landism,
Please review the following commits I made in branch nicks/templating2:
fb6af32d1990157571dfdfbc5bd49de3d29cc8f2 (2022-01-18 12:09:34 -0500)
docs: add a tour of yaml-management solutions
Fixes https://github.com/tilt-dev/tilt/issues/5368
> docs: add a tour of yaml-management solutions

- docs/helm.md
Hello @lianmakesthings, @nicksieger,
Please review the following commits I made in branch nicks/helmresource:
a4656c319235615a6382327ec351191b56ef855a (2022-01-18 15:22:41 -0500)
docs: update the helm docs to recomment helm_resource()
> docs: update the helm docs to recomment helm_resource()

- src/_data/snippets/docker_build_existing_k8s_resource.yml
- src/_data/snippets/docker_build_inline.yml
- src/_data/snippets/docker_build_simple.yml
- src/_data/snippets/docker_compose.yml
- src/_data/snippets/docker_compose_override.yml
- src/_data/snippets/k8s_build_deployment.yml
- src/_data/snippets/k8s_configmap.yml
- src/_data/snippets/k8s_deployment.yml
- src/_data/snippets/k8s_resource_config2.yml
- src/_data/snippets/k8s_secret.yml
- src/_data/snippets/k8s_yaml_custom.yml
- src/_data/snippets/k8s_yaml_simple.yml
- src/_data/snippets/local_go_server.yml
- src/_data/snippets/local_kube_logs.yml
- src/_data/snippets/local_make.yml
- src/_data/snippets/min_k8s_version.yml
- src/_data/snippets/min_tilt_version.yml
- src/_data/snippets/socat.yml
Copy-editing pass on snippet title and descriptions. I think the snippets communicate best when the titles and descriptions have the template "IMPERATIVE-VERB a NOUN-PHRASE", where the imperative verb is not using a passive voice or a weak verb like "Use".
- snippets: edit descriptions for brevity
- snippets: new snippet for injecting image into existing k8s resource
> Snippet Description Edits

- contributing-snippets.md
adds more details on submitting PR to upstream repository
> docs: update details on submitting PR

- docs/multiple_repos.md
- src/_data/docs.yml
Hello @lianmakesthings, @landism,
Please review the following commits I made in branch nicks/multi-repo:
67b87664164d005c7740342f6ebc8e36a60b0136 (2022-02-15 14:41:42 -0500)
docs: how to organize your project for tilt
> docs: how to organize your project for tilt

- blog/_posts/2021-12-03-k8s-custom-deploy.md
- blog/_posts/2022-02-14-preview-environments.md
Hello @nicks,
Please review the following commits I made in branch nicks/typoes:
8db7559173910b0227de9c139bc19a6443c15e70 (2022-02-18 14:59:09 -0500)
fix typoes
> fix typoes

- docs/snippets.md
- src/_data/snippets/down.yaml
Hello @milas,
Please review the following commits I made in branch nicks/down:
f2e3ff49d53a5645d810b6275f4ae5f178595aad (2022-02-24 18:55:18 -0500)
docs: add a tilt down snippet. Fixes https://github.com/tilt-dev/tilt.build/issues/811
> docs: add a tilt down snippet. Fixes https://github.com/tilt-dev/tilt.build/issues/811

- docs/extensions.md
Hello @lianmakesthings, @landism,
Please review the following commits I made in branch nicks/tiltmodules:
5dba3086675007011f17abee9d546ba933ab44fb (2022-03-03 14:39:56 -0500)
docs: extension upgrade note
> docs: extension upgrade note

- blog/_posts/2021-09-07-rancher-desktop.md
Hi @milas,
- fixes link to rancher desktop blogpost
> fixes link to rancher desktop post

- docs/product_faq.md
- src/_includes/footer.html
- src/about.md
Hello @nicks,
98e85b021745a97705faee3ea020a184e4199151 (2022-05-10 11:04:36 -0400)
site: update the hiring box and team locations
> site: update the hiring box and team locations

- docs/snapshots.md
Hello @milas, @hyu,
Please review the following commits I made in branch nicks/cloud2:
e1a29bf86c67271ad4c535a894391f256b22a7a2 (2022-05-20 16:32:55 -0400)
docs: link to the deprecation announcement blog post
> docs: link to the deprecation announcement blog post

- NOTICE
- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/readme3:
f104254976ed0d20331bc571b199db556fb2c495 (2022-06-23 17:52:45 -0400)
update readme to reflect tilt acquisition
> update readme to reflect tilt acquisition

- docs/tutorial/5-live-update.md
Signed-off-by: Rohan Talip <RohanTalip@users.noreply.github.com>
> Corrected some grammar

- docs/tutorial/5-live-update.md
> Fixed the URL for the web app

- src/_data/github.yml
- src/_data/snippets/require_local_tool.yml
- stars/.gitattributes
- stars/.gitignore
- stars/.yarnrc.yml
- stars/package.json
- stars/yarn.lock
- Configure yarn 3 for stars
- Update `require_tool` to use correct param names
> require tool snippet update

- docs/ci.md
Update of docs to help users not get stuck on [#5964](https://github.com/tilt-dev/tilt/issues/5964)
> Add docs about portforwards

- docs/example_nodejs.md
> docs: fix broken nodejs link

- docs/choosing_clusters.md
fixes https://github.com/tilt-dev/tilt/issues/6437
> docs: add a note about home labs running k3s or k0s

- .github/workflows/deploy.yaml
> deploy on s3

- blog/_config.yml
- docs/_config.yml
- src/_config.yml
- src/_data/github.yml
> jekyll: use pretty permalinks

- src/_layouts/docs-mobile-nav.html
- src/_layouts/docs.html
> docs: update /search to /search.html

- src/_data/github.yml
- stars/.yarnrc.yml
- stars/package.json
- stars/yarn.lock
> stars: update stars

- src/_data/github.yml
- src/_includes/head.html
- src/_sass/tilt-legacy.scss
- src/_sass/tilt.scss
use google fonts instead of typekit
> update the web fonts

- deploy/docs.dockerfile
- docs/search.html
- src/_includes/head.html
- src/_sass/search.scss
> docs: swap out search with pagefind
