tilt-dev/tilt.build

src/index.md
Not tied to this but I feel like the GitHub does not make a good step two. All the relevant information is below the fold on desktop and not visible on mobile.
=> Change homepage call to action to go to install docs

src/_sass/layout.scss
Whelp, this look BETTER at least:
We should maybe shorten the name of that article regardless tho.
=> css: hanging indent for long sidebar entries

api/api.py, src/_includes/api.html
Please review the following commits I made in branch maiamcc/filter-yaml-namespace:
321ed8f2592169a3ecf0162e7588403c4e87492a (2019-02-28 15:57:21 -0500)
add namespace arg to filter_yaml api reference
=> add namespace arg to filter_yaml api reference

Tiltfile, api/api.py, docs/fast_build.md, docs/nodejs_microservice_hotreloading.md, docs/tiltfile_concepts.md, src/_includes/api.html
Hello @jazzdan, @landism,
Please review the following commits I made in branch maiamcc/add-takes-string:
c89db3f0f511e45f69417178339cb9f9c3a0f011 (2019-02-28 15:24:57 -0500)
fb.add may take string (make this default example in docs)
=> fb.add may take string (make this default example in docs) [ch1716]

api/api.py, src/_includes/api.html
Hello @jazzdan, @landism,
Please review the following commits I made in branch maiamcc/rm-localpath-from-docs:
7c33d85bc34caff18d53741e123217cc06c3f4b4 (2019-02-28 16:55:26 -0500)
remove localpath/gitrepo from api reference to clarify type signatures
=> remove localpath/gitrepo from api reference to clarify type signatures

api/api.py, src/_includes/api.html
`filter_yaml` and `k8s_kind` now take an `api_version` parameter, and also their selector params are (mostly) regexes
=> api docs: update reflecting regexes and api_version

api/api.py, src/_includes/api.html
fixing line breaks, making code blocks more visible.
before:
after:
=> tidy api reference for default_registry

api/api.py, docs/resource_assembly_migration.md, docs/tiltfile_concepts.md, docs/tutorial.md, src/_includes/api.html
1. Documenting old `k8s_resource` behavior as `k8s_resource_v1_DEPRECATED` is a bit janky, but I haven't thought of a less bad option.
2. Tossing 2019-05-01 out there as a stake in the ground for removing support for the old behavior.
=> docs: update for workload assembly

docs/docker_compose.md, docs/live_update_reference.md
Hello @nicks,
Please review the following commits I made in branch nicks/restart:
839470b685ef0ec7e488ba8265753d3937199cfe (2019-04-12 16:57:30 -0400)
fix typo in live update docs and update docker_compose docs
=> fix typo in live update docs and update docker_compose docs

docs/nodejs_microservice_hotreloading.md
It seems there is an extra `)`.  If copied and pasted, this will turn into a parsing issue. Hoping to remove
=> Removing extra `)`

docs/nodejs_microservice_hotreloading.md
Hello @nicks,
Please review the following commits I made in branch nicks/typo:
9630f70c6d1ad1062e731a3057a0b7acd6e4b2ca (2019-04-26 13:42:25 -0400)
fix a typo in the frontend doc
=> fix a typo in the frontend doc

api/api.py, src/_includes/api.html
Hello @dmiller, @lredd,
Please review the following commits I made in branch maiamcc/read-yaml-api-doc:
f2c341048ac5b9e2b27bd4246adeebc289edd929 (2019-05-01 11:18:43 -0400)
api: docs for new read_yaml func
=> api: docs for new read_yaml func

api/api.py, src/_includes/api.html
I'm guessing this is copypasta from the k8s_kind example.
=> api: remove k8s_kind from custom_build example

docs/upgrade.md, src/_data/docs.yml
This is basically just the installation doc, plus a link to the releases page, minus a bunch of stuff that isn't relevant to upgrades.
This will make bumping the version for docs more annoying, since now there are two pages to update. I'm tempted to write a script.
=> docs: add upgrade instructions

docs/nodejs_microservice_hotreloading.md
The api now uses an `[]` array param but the docs still list multiple params
Small doc fix.
=> docs: update node example readme

blog.dockerfile, docs.dockerfile, site.dockerfile
Hello @nicks,
Please review the following commits I made in branch nicks/dockerfile:
db140d9047eb77da963614b163c2a2e462e20b02 (2019-05-15 16:04:01 -0400)
don't use globs because it hurts docker caching
=> don't use globs because it hurts docker caching

src/_sass/layout.scss
Hello @yuindustries,
Please review the following commits I made in branch nicks/squares:
29e153b6cc89903cad30fcb5fc9f1166b3901f16 (2019-05-15 16:04:57 -0400)
form: make options squares instead of circles
=> form: make options squares instead of circles

api/api.py, src/_includes/api.html
=> api: note that fast_build is deprecated rather than linking to non-existant docs

serve.yaml
Please review the following commits I made in branch nicks/probe:
69c2e93cd4328678bc5c0f56293c4de6040677de (2019-06-13 12:18:33 -0400)
k8s: add readiness probes to jekyll servers
=> k8s: add readiness probes to jekyll servers

serve.yaml
Hello @nicks,
Please review the following commits I made in branch nicks/health:
5da730982229f914fb6823b1ea90ed003e1e1d41 (2019-06-13 17:34:30 -0400)
Revert "k8s: add readiness probes to jekyll servers (#173)"
This reverts commit 6161f6f6c9f6007283a30349bb45291479294644.
=> Revert "k8s: add readiness probes to jekyll servers (#173)"

healthcheck.sh
Hello @nicks,
Please review the following commits I made in branch nicks/health2:
62f0dd2bc1fba008bec581346c1bb01a8e1ae52c (2019-06-24 11:25:49 -0400)
remove jekyll build health check. this is too slow
=> remove jekyll build health check. this is too slow

docs/multiple_clusters.md
The documented example for "Don't Touch Prod" fails to function in my environment. However, whenever I add `()` to align with the API reference for `k8s_context()`, the example code functions as intended.
=> Update "Don't Touch Prod" example

docs/live_update_reference.md
Hello @nicks, @dbentley,
Please review the following commits I made in branch maiamcc/spoof-container-restart:
7ba7d4f360724517dd5a9cd4beaf472953413362 (2019-07-05 17:06:38 -0400)
docs: link to scripts to spoof restart_container on non-docker runtimes [ch2861]
=> docs: link to scripts to spoof restart_container on non-docker runtimes [ch2861]

api/api.py, src/_includes/api.html
Hello @landism, @nicks,
Please review the following commits I made in branch maiamcc/override-command:
a362d537153e11776ba5d191e5b18552fc6d6638 (2019-07-11 16:48:37 -0400)
api: entrypoint param for docker_build and custom_build
=> api: entrypoint param for docker_build and custom_build [ch2886]

docs/integrating_bazel_with_tilt.md
Currently `custom_build` watch for just label changes on bazel workspace. This PR fixes to watch for source file changes
fixes #236
=> doc(bazel): watch for files changes not labels.

api/api.py, src/_data/api_functions.yaml
I struggled a bit to figure out why my `container_restart` method wasn't working it turns out the API docs don't seem to match the code. 
https://docs.tilt.dev/api.html#api.restart_container . 
Hopefully this fixes that.
=> Fix container restart method name

Tiltfile
Please review the following commits I made in branch maiamcc/local-resource:
a43a03a77771ecbafe013611d9e259aef2a5e1d1 (2019-09-24 15:54:42 -0400)
run make-api as local_resource to speed up tiltfile
=> run make-api as local_resource to speed up tiltfile

api/api.py, src/_data/api_functions.yaml, src/_includes/functions.html
Please review the following commits I made in branch maiamcc/docker-prune:
d37bec0a6cc066ce9492fe39ca768f376f491fe5 (2019-10-15 13:54:17 -0400)
docs: API ref for docker_prune_settings
=> docs: API ref for docker_prune_settings

api/api.py, src/_data/api_functions.yaml, src/_includes/functions.html
It's probably fine to get rid of the "k8s_resource_v1_DEPRECATED" eyesore at this point
=> docs: undocument resource_assembly_version

docs/partner_program.md, docs/telemetry_faq.md, src/_data/docs.yml
Hello @dbentley, @jazzdan,
Please review the following commits I made in branch nicks/telemetry:
7101eb782d896c6f826f2fcd54622acf75fb6b6d (2019-11-14 20:48:25 -0500)
docs: move telemetry info to its own guide, so we can link to it from the readme
=> docs: move telemetry info to its own guide, so we can link to it from the readme

docs/install.md
Just a small improvement: users of Homebrew do not need to care about the `brew tap` step since `brew install windmilleng/tap/tilt` will implicitely run `brew tap` if the tap has not already been cloned.
Just want to say: awesome project! 🤩
=> homebrew: no need to brew tap, brew windmilleng/tap/tilt is enough

api/api.py, docs/tiltfile_concepts.md, src/_includes/functions.html
Matt Hodgekins at Datadog got tripped up b/c he didn't realize Tilt
automatically did most of the k8s resource config for you, asked us
to clarify our docs around this. While I was in here, I updated
Tiltfile Concepts: Resources to be more in line with our new definition
of "resource" (i.e. one that includes both K8s resources and local resources)
=> api/docs: update tiltfile concepts with new understanding of resource, clarify k8s_resource api docs

docs/live_update_reference.md
Hello @landism, @nicks,
Please review the following commits I made in branch maiamcc/live-update-clarify:
db8c79f02078d36b0c5e78f2b882b072808ac6d6 (2019-11-25 16:46:18 -0500)
docs: clarify that live_update only happens on second build and beyond [ch3910]
=> docs: clarify that live_update only happens on second build and beyond [ch3910]

docs/install.md, docs/upgrade.md
Hello @nicks,
Please review the following commits I made in branch nicks/bump:
bf8fea4c79bf4d74680dfc4f21a1ec121ea24aae (2020-01-06 17:19:48 -0500)
update: bump default version to v0.10.26
=> update: bump default version to v0.10.26

api/api.py, src/_data/api_functions.yaml, src/_includes/functions.html
i feel like this information (or at least, how to disable parallel updates)
should live somewhere more accessible in the docs, and I can't figure out
where makes sense... maybe an FAQ for "Tilt is doing to much at once, how
do i make it stop?"?
=> api: add update_settings to api docs

Makefile
Without buildkit, a fully cached build takes 15-30 seconds, mostly spent transferring the build context to the docker daemon.
I haven't looked into how, but apparently buildkit somehow optimizes that away, so a build only takes 1-3 seconds.
=> tilt.build: use buildkit when building api image

api/api.py, src/_includes/functions.html
Please review the following commits I made in branch nicks/ssh2:
d0fea62d1e193c4e1212c7ee1f71764e761b5ae9 (2020-01-13 16:14:17 -0500)
api: add docker_build(ssh='default') to api docs
=> api: add docker_build(ssh='default') to api docs

blog/_posts/2019-11-15-local-resource.md
Happened to run across these while researching a user support request.
=> Fix two broken links in Local Resource announcement

Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/deps:
be2728f7049b669a0a2835c0db340dc1151487dd (2020-01-24 16:08:36 -0500)
tiltfile: all jekyll services should block on the 'make api' job
it produces files that they consume
=> tiltfile: all jekyll services should block on the 'make api' job

docs/tiltfile_concepts.md
The `+` on the newline was messing up formatting.
=> Fix paragraph layout in Tiltfile Concepts

docs/tiltfile_config.md
The tiltfile_config.md code examples use 2-space indentation. For whatever reason, these get translated variously as 0-space or 2-space indentations in HTML.
Changing them all to 4-space in the MD makes them all translated to 2-space indentations in the HTML 🤷‍♂ 
I looked through all the other python blocks in the docs dir and didn't see any other instances of this problem.
=> tiltfile config: fix indentation

api/api.py, src/_includes/functions.html
Please review the following commits I made in branch nicks/network:
3e423b4c500f3fa5153e697e2af463bd1db2e9d8 (2020-01-27 16:50:45 -0500)
api: add documentation on docker_build(network=...)
=> api: add documentation on docker_build(network=...)

docs/example_projects.md
Looks like the doc may be out of date:
=> Fix quit command in getting started

api/api.py, src/_data/api_functions.yaml, src/_includes/functions.html
also:
1. `decode_yaml` was in the docs twice
2. the type of `read_yaml`'s `default` was wrong
=> api docs: add read/decode/encode_yaml_stream

docs/live_update_reference.md
Hello @nicks,
Please review the following commits I made in branch nicks/issue3037:
0e6a73ee4f3991a7cb898f85e3087c04395066f2 (2020-03-02 10:40:45 -0500)
docs: fix references to container images in the illustration. Fixes https://github.com/windmilleng/tilt/issues/3037
=> docs: fix references to container images in the illustration. Fixes https://github.com/windmilleng/tilt/issues/3037

docs/faq.md
Please review the following commits I made in branch nicks/faq2:
e2832c1b6ff96da7be921712241f621029c546c3 (2020-03-03 14:32:41 -0500)
docs: add error message faq on unused image
=> docs: add error message faq on unused image

docs/api.md
lots of really with-it users (e.g. [Tom Elliott](https://kubernetes.slack.com/archives/CESBL84MV/p1583872879153900?thread_ts=1583868658.149400&cid=CESBL84MV)
didn't know this was a thing
=> link to starlack spec at top of API reference

docs/example_python.md, docs/example_static_html.md, src/_sass/layout.scss
Hello @nicks, @landism,
Please review the following commits I made in branch maiamcc/fix-centered-table:
f3217ece541badf1c3a76f3443c697e5d6e3ac15 (2020-03-11 18:12:24 -0400)
css/example guides: isolate css changes to tables so they don't affect api docs
=> css/example guides: isolate css changes to tables so they don't affect api docs

api/api.py
This updates the code comment for `yaml_filter` and adds a separate example of an exact name match.
Happy to make some modifications if someone thinks there's a clearer way to express this.
=> Clarify that yaml_filter uses regex-matching

docs/example_go.md
Hello @nicks,
Please review the following commits I made in branch nicks/goformatting:
74f50c16cebb6781b8b87594c800039738f9168a (2020-03-17 19:55:48 -0400)
docs: fix example go formatting
=> docs: fix example go formatting

docs/debuggers_python.md, src/_data/docs.yml
i'd hoped to also include `web-pdb` in this example (or at least in the
example repo) but [my PR to make web-pdb useful on servers/threaded things](https://github.com/romanvm/python-web-pdb/pull/20)
hasn't been released/I can't tell when it will be
=> docs: python debugger guide [ch5148]

docs/teams.md
See https://app.clubhouse.io/windmill/story/6059/docs-only-team-owner-can-access-team-page
=> docs: Team page only accessible by team owner

api/api.py, docs/custom_build.md, docs/file_changes.md, src/_includes/api/functions.html
a user in #tilt expressed confusion with the docs on `ignore` and `only`
(e.g. they didn't know what directory they're evaluated relative to).
This PR attempts to clarify the API docs and the File Changes Guide
on this point.
=> docs: clarify docs for ignore and only params

docs/live_update_reference.md
there's a small typo fix 
also I am trying to get the 3-level nested list of "when a file changes" steps to look better by breaking out the roman numeral'd items into true markdown numeric list items
Right now my changes look good in github's markdown, but I don't know how docs.tilt.dev will render them.
=> typo fix and adjusting formatting of list

docs/file_changes.md
Just a typo in the `ignore` section
=> Fix wrong parameter in docs/file_changes.md

api/api.py, src/_includes/api/functions.html
Please review the following commits I made in branch nicks/pruner:
22cba109a5c0ba8346e126d92cebedc1caf2e71a (2020-04-21 13:22:09 -0400)
api: add documentation on keep_recent pruner option
=> api: add documentation on keep_recent pruner option

blog/_config-dev.yml, blog/_config.yml, docs/_config-dev.yml, docs/_config.yml, docs/index.md, src/_config-dev.yml, src/_config.yml, src/_includes/cta_docs.html, src/_includes/footer.html, src/_includes/header.html, src/_includes/preview.html, src/_layouts/blog.html, src/index.md, src/post-subscribe.md
Hello @nicks,
Please review the following commits I made in branch nicks/robots:
cbd2f55ae250f7f20215af2bfbe1d3c636afcba8 (2020-04-27 17:53:13 -0400)
all frontmatter urls should omit the trailing '/', per recommendation here: https://jekyllrb.com/docs/variables/ this makes some SEO stuff work better
=> all frontmatter urls should omit the trailing '/', per recommendation here:

docs/snapshots.md
Based on https://app.clubhouse.io/windmill/story/6731/when-disable-snapshots-is-set-usage-is-not-captured-in-tilt-cloud-team-page#activity-6782
=> Specify snapshot data in FAQ entry about disabling snapshots

api/api.py, src/_includes/api/functions.html
we should maybe eventually bring `local_resource.cmd` into sync with `local.command` and `custom_build.command`, but for now at least make the documentation accurate
resolves [tilt#3278](https://github.com/windmilleng/tilt/issues/3278)
=> api ref: correct parameter name for local.command [ch6846]

docs/teams.md
1. Communicate the behavior implemented for [CH6848](https://app.clubhouse.io/windmill/story/6848/figure-out-what-to-do-with-versions-and-nudges-to-launch-in-a-non-confusing-way)
2. Try to prevent Lauras from expecting that they click promote and Friedas immediately get notified of the new Tilt, and then thinking it's broken when that doesn't happen (which isn't to say the current behavior is ideal, but let's at least set expectations)
=> docs: add footnote about min suggested version. also clarify notification timing.

docs/example_csharp.md, docs/example_go.md, docs/example_java.md
Please review the following commits I made in branch maiamcc/update-ex-guides-restart_process:
061cf97b5ea118d27de643a7f832360c3815d77e (2020-05-15 19:22:23 -0400)
guides: update guides to reflect restart_process extension instead of entr hack for restarting
=> guides: update guides to reflect restart_process extension instead of entr hack for restarting

src/index2.md
Wrong class names broke these cute icons.
=> site: fix missing Resources icons

src/_sass/header2.scss
It scales up a bit. Wasn't working properly because of mis-applied CSS.
=> site: fix subtle hover effect for the Tilt logo

src/_sass/home2.scss
| Before | After |
| --- | --- |
| <img width="408" alt="Screen Shot 2020-06-03 at 2 26 00 PM" src="https://user-images.githubusercontent.com/10860550/83675850-b7ccdf80-a5a7-11ea-9e81-25d61536cfd9.png"> | <img width="406" alt="Screen Shot 2020-06-03 at 2 25 29 PM" src="https://user-images.githubusercontent.com/10860550/83675849-b7ccdf80-a5a7-11ea-90cd-06c052d00375.png"> |
=> site: nowrap for `tilt up` on landing page for mobile

docs/helm.md
Please review the following commits I made in branch nicks/helmremote:
812910048a79d9838e5454251d2a6a2747bcff77 (2020-06-05 15:01:48 -0400)
docs: replace our helm-remote tutorial with a reference to the extension
=> docs: replace our helm-remote tutorial with a reference to the extension

docs/api.md
Hello @victorwuky, @ellenkorbes,
Please review the following commits I made in branch nicks/extensions:
89080e05a6336cf6d95ee286d601cedb609e284d (2020-06-05 14:54:51 -0400)
docs: add links to extensions from the api reference
=> docs: add links to extensions from the api reference

api/api.py, src/_includes/api/functions.html
Please review the following commits I made in branch maiamcc/restart-container-api:
242bba4f1763d5969346d86de7871de98c06c01a (2020-06-12 12:16:20 -0400)
api: restart_container for docker compose only, add links
=> api: restart_container for docker compose only, add links

docs/install.md
The line to invoke the web request for installing on windows didn't have matching parenthesis. This is the fix for that.
=> Fix syntax err on win install cmd

docs/contribute_extension.md
Please review the following commits I made in branch maiamcc/extension-pr-prefix:
5c1ad1cff52a13d9812552e386f567937c42c73f (2020-06-29 17:33:46 -0400)
docs: extension PRs should be prefixed with extension name
=> docs: extension PRs should be prefixed with extension name

docs/snapshots.md
See https://app.clubhouse.io/windmill/story/8079/tiltfile-failures-allow-users-to-unintentionally-create-public-snapshots#activity-8153.
=> docs: Put set_team as the first line of Tiltfile

docs/example_java.md
a user question in #tilt made me realize that we don't link to all
our java examples in all the places we could!
=> docs: link other java examples from repo in java guide

docs/api.md
The TitlFile API Reference now has `min_k8s_version()` is now listed on the extensions section
=> docs: updated list of extensions with min_k8s_version()

docs/debug_faq.md
saw a user confused by these docs, not understanding that the sample
invocation was a placeholder, etc. I tried to clarify the examples
as well as indicating up front what Tilt is sending.
=> docs: clarify experimental_telemetry_cmd docs

api/api.py
https://github.com/tilt-dev/tilt/pull/3614
=> docs: Krucible as recognized dev cluster

api/api.py, docs/custom_resource.md, src/_includes/api/functions.html
Hello @jazzdan, @maiamcc,
Please review the following commits I made in branch nicks/podreadiness:
bc8e6fb4dd5169e5c77ec66ce746109403e87780 (2020-07-31 13:18:33 -0400)
docs: add docs on pod_readiness
=> docs: add docs on pod_readiness

api/api.py, src/_includes/api/functions.html
Hello @victorwuky,
Please review the following commits I made in branch nicks/cachefrom:
c929082c0303c0ec99f745653f66cfe5f1df57eb (2020-07-31 13:26:11 -0400)
docs: add api docs for cache_from, pull
=> docs: add api docs for cache_from, pull

docs/install.md
We ran this experiment for a month and never got any clicks,
let's remove the clutter.
=> docs: remove calendly link from the install page

src/_sass/home.scss, src/index.md
One issue — Firefox complains "www.youtube.com will not allow Firefox to display the page if another site has embedded it." It works in Firefox Private Browsing and in Chrome and Safari, though.
=> Add Tilt in Two Minutes video

src/index.md
Fun fact! If you enable this setting when embedding a YouTube video...
...Firefox may refuse to show the embedded video and display this error!
```
To protect your security, www.youtube.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.
```
=> site: fix YouTube display on Firefox

src/enterprise.md
Copying over from https://github.com/tilt-dev/tilt.build/blame/master/src/index.md#L100
---
=> site: Schedule a demo popup on enterprise page

src/_sass/home.scss
Could not reproduce it on Chrome/Safari on mac (using the developer tool console). But verified this on my physical iPhone 11. And debugged it using remote mobile web dev (i.e. connected phone to computer and ran the inspector on my computer against mobile safari running on phone).
| Before | After |
| --- | --- |
| ![IMG_3698](https://user-images.githubusercontent.com/10860550/89849005-982cd700-db55-11ea-8ae2-4e5278142d2d.PNG) | ![IMG_3699](https://user-images.githubusercontent.com/10860550/89848977-851a0700-db55-11ea-966d-3154472ceae7.PNG) |
=> site: Fix Schedule a demo button text so it is not clipped on mobile

docs/install.md, docs/upgrade.md
[asdf](https://github.com/asdf-vm/asdf) is a useful tool for managing CLI tools. This PR updates the documentation to detail how to install tilt via asdf.
=> Adds instructions to install tilt via asdf

docs/custom_resource.md
Hello @nicks,
Please review the following commits I made in branch nicks/prometheus:
455c308ed4ef84ede4f966baad779158712334d7 (2020-08-26 17:12:23 -0400)
fix a typo
5143c003361129a1696db8de78a5d6d4ce07772a (2020-08-26 17:01:35 -0400)
docs: add a note on the prometheus example
=> fix a typo

stars/inject_stars.sh
this script has been leaving behind "github.yml-e" files on my mac
=> tilt.build: fix inject_stars on bsd

docs/choosing_clusters.md
add missing `&&` and line break to microk8s setup instructions in "choosing a cluster"
=> fix microk8s setup instructions

docs/experimental_analytics_report.md
We only expect people to use this function in coordination with us. As such, it is documented on an unlinked page and is not listed in the main api docs. Account managers can choose to show or not show this page to customers, but this at least exists to give context to account managers.
=> docs: document experimental_analytics_report

docs/api.md
Hello @nicks,
Please review the following commits I made in branch nicks/filesynconly:
36f04f146ca9b63ee854b36c2a78fb55fbf1bab1 (2020-09-11 10:23:06 -0400)
add file_sync_only extension to the api page
=> add file_sync_only extension to the api page

docs/api.md
Hello @nicks,
Please review the following commits I made in branch nicks/prometheus2:
b003e7b2705ecfb0efae8ab33c7b53c13e173efc (2020-09-16 18:46:07 -0400)
add the coreos_prometheus extension to the api docs
=> add the coreos_prometheus extension to the api docs

api/api.py, docs/custom_build.md, src/_data/github.yml, src/_includes/api/functions.html
63f3eaff7dddc571edf20d0d47e9de7157e350b2 (2020-09-16 13:57:30 -0400)
add docs on outputs_image_ref_to in v0.17.5
=> add docs on outputs_image_ref_to in v0.17.5

docs/choosing_clusters.md, docs/install.md
Please review the following commits I made in branch nicks/ch9397:
5dde607b70ae6b2dbebeda0d491c08f9c09f1863 (2020-09-16 18:36:34 -0400)
docs: change the default cluster instructions to recommend Kind on Linux
Fixes https://github.com/tilt-dev/tilt/issues/3772
=> docs: change the default cluster instructions to recommend Kind on Linux

docs/rollout/introduce-tilt.md, src/_data/rollout.yml
Re-org and flesh out the Introduce Tilt doc.
This started as a copy-edit, I ended up making more changes here than anticipated whoops, but i think it adds a lot of useful context / squeezes in some other docs tips we've discussed in the past.
Also cleaned up a lot of typos/clarity stuff
=> rollout: flesh out/clean up Introduce Tilt doc

docs/api.md
Hello @nicks,
Please review the following commits I made in branch nicks/snyk:
d1541551c166837d796b6744d22b783da3dc40e6 (2020-09-21 19:30:27 -0400)
add snyk extension to api docs
=> add snyk extension to api docs

docs/tiltfile_concepts.md
fixes https://github.com/tilt-dev/tilt/issues/3813
I think the reporter's expected behavior (the workload arg is an object selector) is better than the current behavior (the workload arg must exactly match the auto-generated name). I looked briefly into changing the code to have that behavior instead. 1) it was non-trivial and 2) we're not super excited to further commit to the notion of this object selector syntax.
So, I decided to just document the existing suboptimal behavior.
=> docs: clarify workload arg is not an object selector

api/api.py, src/_includes/api/functions.html
Hi there 👋 
I've been using this framework recently as a dive into making our micro-service development easier. Love what you all have build!
Just addressing a small change in the documentation. It seems "link_text" doesn't work and the "name" does. Just want to see if this was a problem. For example: 
```
k8s_resource('cool-service',
port_forwards=[
port_forward(8080, container_port=8080, name='rest-api'),
port_forward(8081, container_port=5858, name='node-debugger')
],
resource_deps=['cool-service-db']
)
```
Thanks for all the hard work!
=> Match the documentation for port_forward args

api/api.py, src/_includes/api/functions.html
Hello @nicks,
Please review the following commits I made in branch maiamcc/args-not-attributes:
0f145b2f3e51ae1f55d4dcef3e7643f6ba2bb600 (2020-10-19 14:29:39 -0400)
api: use 'args' not 'attributes' to specify function args
=> api: use 'args' not 'attributes' to specify function args

api/api.py, blog/_posts/2019-09-09-commit-of-the-month-august.md, docs/choosing_clusters.md, src/_includes/api/functions.html, src/_includes/functions.html
Changes wording in Documentation / Blog Post from using the term 'whitelist' to the term 'allow', creating better matching internal code feature phrasing and community inclusiveness.
=> docs: Inclusive wording changes

docs/choosing_clusters.md
`KUBECONFIG` was set but not actually used.
An alternative to this PR is to `export KUBECONFIG=...` to keep the lines short, but that could have side-effects.
=> docs: Fix command to use microk8s cluster

docs/index.md
Copying from https://github.com/tilt-dev/tilt.build/edit/master/docs/tutorial.md.
=> docs: Pull practice guides from data file

docs/custom_build.md
On Tilt v0.17.11, as documented, the `ignores` key will throw an error
Using `ignore` is accepted
=> fix typo in `custom_build` args `ignore` key

docs/choosing_clusters.md
=> Fix a typo in microk8s

api/api.py, src/_data/github.yml, src/_includes/api/functions.html
Hello @maiamcc, @ellenkorbes,
Please review the following commits I made in branch nicks/portforward:
78fe764de51f21de9f2783d4b1a4b747e7761794 (2020-12-02 11:27:12 -0500)
document the host parameter on port-forwards
=> document the host parameter on port-forwards

docs/index.md
Hello @victorwuky,
Please review the following commits I made in branch nicks/security:
3679ec8da25d8ceb1e504aed4144f360aaa4f358 (2020-12-18 12:19:01 -0500)
docs: also add the security policy to the docs site
=> docs: also add the security policy to the docs site

api/api.py, src/_data/api/functions.yaml, src/_includes/api/functions.html
Please review the following commits I made in branch nicks/ch10608:
856207a11320ababc0828c5f7e9bf33d6b5fbb00 (2021-01-05 14:05:25 -0500)
docs: add docs for warn()
=> docs: add docs for warn()

docs/index.md
Last week, different people in #tilt didn't seem aware of Tilt Extensions related to their issues. Let's talk up Extensions in our docs more!
=> docs: add info on Extensions

api/api.py, docs/local_resource.md, src/_data/api/classes.yaml, src/_data/api/functions.yaml, src/_data/github.yml, src/_includes/api/classes.html, src/_includes/api/functions.html
(⚠️ This screenshot is slightly outdated, arg order changed to `port: int, host: str='localhost'`)
(⚠️ This screenshot is slightly outdated, arg order changed to `port: int, host: str='localhost'`)
=> docs: add readiness_probe for local_resource to docs + API

api/api.py, src/_includes/api/functions.html
The default here is `False` (i.e. enable Docker prune); the docs
were incorrect.
=> docs: fix default value for disable in docker_prune_settings

api/api.py, src/_includes/api/functions.html
This got missed in #805. The `probe()` function + all the dependent types were included in API reference, but `readiness_probe` was missing from the `local_resource` function signature 😵 
Closes #812.
=> docs: update local_resource signature to add readiness_probe

Tiltfile
Hello @landism, @maiamcc,
Please review the following commits I made in branch nicks/cache:
356e69aefc9b3b74a8401396c8f465a997fba99a (2021-02-12 19:04:19 -0500)
tiltfile: add a cache_from param to share images
=> tiltfile: add a cache_from param to share images

docs/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/ux-research:
548db6f58bb1aef8f2351f936e5ccdb503eec5f1 (2021-03-19 19:42:48 -0400)
docs: add ux research link to docs.tilt.dev too
=> docs: add ux research link to docs.tilt.dev too

docs/ci.md, src/_data/docs.yml
Hello @maiamcc, @ellenkorbes,
Please review the following commits I made in branch nicks/ci3:
e3cfdb6d20fc8efafd1792f43a5dd5fe7ed67bb6 (2021-04-06 11:13:20 -0400)
docs: add docs on how to set up tilt on ci
This basically cannibalizes the blog post
https://blog.tilt.dev/2021/04/02/kubernetes-on-ci.html
and other CI docs into a central docs, in the spirit
of cannibalizing content more often
=> docs: add docs on how to set up tilt on ci

docs/upgrade.md
Hello!
I believe that `brew install` is not required when upgrading tilt using homebrew because `brew upgrade tilt-dev/tap/tilt` already installs the latest version.
I get this warning when I run `brew install` (after running `brew upgrade`):
$ brew install tilt-dev/tap/tilt
Warning: tilt-dev/tap/tilt 0.19.5 is already installed and up-to-date.
To reinstall 0.19.5, run:
brew reinstall tilt
=> Remove brew install from upgrade docs

blog/_posts/2021-04-30-how-many-servers.md
Hello @nicks,
Please review the following commits I made in branch nicks/cli:
feae2add8faf4e4de70d6ffc4c564c7832fd9a05 (2021-04-30 14:56:02 -0400)
blog: update post to use 'tilt get' instead of 'tilt describe'
=> blog: update post to use 'tilt get' instead of 'tilt describe'

src/_data/footer.yml, src/_data/github.yml, src/_data/header.yml, src/_includes/index_cta.html, src/liftoff.md
Hello @hyu,
Please review the following commits I made in branch nicks/cta:
d2aae90e2af2b093f8a473520f045aec92338266 (2021-05-12 18:22:10 -0400)
site: replace enterprise page with a 'tilt shift' page
=> site: replace enterprise page with a 'tilt shift' page

blog/_posts/2021-05-18-entr-the-dragon.md
Hello @nicks,
Please review the following commits I made in branch nicks/entr2:
31619e4b02b64989c465de5a54af24c2f1a30715 (2021-05-18 12:53:31 -0400)
blog: use find instead of ls
=> blog: use find instead of ls

api/api.py, blog/_posts/2019-11-15-local-resource.md, docs/local_resource.md, docs/manual_update_control.md, src/_includes/api/functions.html
Previously, you could not have a resource that had `auto_init=False`
with `trigger_mode=TRIGGER_MODE_AUTO`. This restriction was lifted
in v0.19.1 a while back by https://github.com/tilt-dev/tilt/pull/4292.
This removes mention of the restriction from the docs including
retconning a blog post from 2019.
=> docs: remove auto_init=False / TRIGGER_MODE_AUTO restrictions

api/api.py, src/_includes/api/functions.html
* `watch_file` can (recursively) watch directories despite its
name
* `listdir` _only_ watches if `recursive=True`; otherwise, it
just returns a listing of the top-level directory but does
not add a watch
=> docs: clarify watch behavior for listdir & watch_file

docs/index.md
Hello @nicks,
Please review the following commits I made in branch nicks/cloud:
031bba0af1bff91aa349c9ce4ab05b1258dacecc (2021-07-02 18:40:21 -0400)
docs: remove tilt cloud from readme frontpage, per https://github.com/tilt-dev/tilt/pull/4718
=> docs: remove tilt cloud from readme frontpage, per https://github.com/tilt-dev/tilt/pull/4718

blog/_posts/2021-06-21-uibutton.md
Was asked about this on Twitter - blog post is vague here! (The
extension docs also didn't do a great job of clarifying this and
are being updated too.)
This just adds a note that the execution happens locally (not in
a Pod/container) and an extra call-out to the extension docs.
=> blog: add execution clarification for uibutton

src/_data/docs.yml, src/_layouts/docs.html, src/_sass/base.scss, src/_sass/docs.scss, src/_sass/layout.scss
We've got a LOT of docs, but most of the time when folks end up
on the docs site, they probably want the API or CLI reference,
which are waaaay at the bottom.
This adds a subnav that includes a few links to the (hopefully)
most important pages. The search comes along for a ride out of
the sidebar as well.
There were some...interesting things going on with the layout,
so there's some general changes here to flexbox more flexbox-y,
but they should not actually change things, just make it more
friendly for future adaptions (like this one).
I did a sanity pass across all the pages on the docs site as well
as a few blog posts and whatever I could find on the "main" site.
Thanks to @lucieleblanc for proposing this! 🙌
=> docs: add subnav with top reference pages

docs/index.md, src/_data/github.yml, src/_includes/index_cta.html
Hello @nicks,
Please review the following commits I made in branch nicks/office-hours:
f50f0f1358d06b5097aaa7073088820db8df35df (2021-07-09 18:29:39 -0400)
docs: add office hours to docs and liftoff page
=> docs: add office hours to docs and liftoff page

docs/choosing_clusters.md
Previous value https://github.com/tilt-dev/ctlptl#kind-with-a-built-in-registry is not a valid anchor on the README anymore.
=> Fix Kind Setup Link

docs/choosing_clusters.md
This patch fixes a minor typo in the docs that keeps a link from rendering correctly.
=> docs: Fix URL typo

blog/_posts/2019-02-18-how-i-built-a-simple-static-jekyll-site-without-installing-ruby-a-rant.md, deploy/blog.dockerfile, deploy/docs.dockerfile, deploy/site.dockerfile, docs/skaffold.md, src/Gemfile, src/Gemfile.lock
Using https://github.com/keithmifsud/jekyll-target-blank which
automatically adds this for all external links.
Also fixed a couple broken links it flagged and added `--trace`
to the Docker entrypoints to make issues easier to track down
when Jekyll goes :boom:.
=> site: open all external links with target="_blank"

src/_sass/layout.scss, src/assets/js/links.js
This behavior mimics how GitHub (and many other sites) behave,
which is a pretty familiar pattern for users.
The entire header is a permalink now, and the '🔗' shows up on
hover (replacing `►`).
(As a sidenote, the permalink functionality does not really need
Javascript - we should arguably rewrite this as a Jekyll include
to set up the permalinks at generation time, but at the same time,
functionality without it isn't hugely degraded, so it's not worth
it right now.)
=> docs: make entire header a permalink

src/_sass/layout.scss
On scroll, the sidebar nav will stay sticky at the top of the
screen.
You can still scroll to the bottom of the content area (i.e. the
footer links) and it _will_ scroll out at that point. This behavior
is pretty consistent with other sticky navs on a few docs sites I
played with.
=> docs: sticky sidebar nav

src/Gemfile, src/Gemfile.lock
Remove the `jekyll-target-blank` plugin which was recently added
in #902 to open all external links in a new window.
Unfortunately, nokogiri (the underlying Ruby lib that parses the
HTML) doesn't support XML namespaced elements properly, so was
converting `<gcse:searchresults-only>` -> `<searchresults-only>`
when processing the DOM to modify outbound links.
=> docs: fix search

docs/ci.md
Hello @milas,
Please review the following commits I made in branch nicks/session:
23f7b5847972c1cefeb416055baa9624cccb5048 (2021-08-23 12:57:43 -0400)
docs: add info on the Session object to 'tilt ci' docs
=> docs: add info on the Session object to 'tilt ci' docs

docs/search.html, src/Gemfile, src/Gemfile.lock
Re-add the `jekyll-target-blank` plugin but adjust the Google Custom
Search so that it doesn't break it.
The search fix is to use a `<div>` instead of the custom
`<gcse:searchresults-only>` element (which was erroneously having its
`gcse` "namespace" chopped off by nokogiri during DOM processing). This
is actually the way that Google has it in their docs now as of Aug 2021
and works fine.
While it's not great that nokogiri can't handle this properly, the
likelihood we use custom elements in the future with prefixed namespaces
is minimal, and the alternatives are:
* Use JS to add `target="_blank"` to all links on page load
* Remember to specify it manually on all external links
=> docs: re-enable links opening in external window

docs/index.md, src/_includes/index_cta.html
We've decided to put this on hold for now!
I reverted to the copy before the introduction, which has the Calendly for user research. If that's not what we want as a substitute for now, just lemme know what makes sense to replace it with!
=> site: remove office hours experiment

api/api.py, src/_includes/api/functions.html
Please review the following commits I made in branch nicks/unused:
2c341e1deb03678e7efb0ce6c87664442d3d8895 (2021-09-03 16:30:58 -0400)
api: add docs for suppress_unused_image_warnings
=> api: add docs for suppress_unused_image_warnings

Tiltfile, docs/debug_faq.md
I left the content about `experimental_telemetry_cmd` since that's still functional/supported - feel free to change as you see fit.
=> docs: remove references to `experimental_metrics_settings`

docs/tiltfile_config.md
This is implicitly covered throughout the page, but I wanted a
dedicated section for clarification and to link to on Tiltfile
errors.
=> docs: add section on positional args

blog/_posts/2021-09-07-rancher-desktop.md
We got a user-contributed `kim_build` extension!
https://github.com/tilt-dev/tilt-extensions/tree/master/kim
Let's promote it and save readers some time if they just
want to get going with `kim` + Tilt 🙃
=> blog: update Rancher Desktop blog post with extension

src/_data/docs.yml, src/_layouts/docs.html, src/_sass/docs.scss
From the nav, sections can have "in-section" nav which adds
previous and next links (based on sidebar order).
For now, this will just be used for the tutorial.
=> docs: add in-section nav for tutorial

api/api.py, docs/custom_build.md, src/_data/docs.yml, src/_includes/api/functions.html
Hello @chimney42,
Please review the following commits I made in branch nicks/builders:
335694a8d0284e08d4a79dc8d95be57472d90d56 (2021-11-09 15:12:34 -0500)
docs: integrate https://github.com/tilt-dev/tilt-example-builders into the custom image builder guide
=> docs: integrate https://github.com/tilt-dev/tilt-example-builders into the custom image builder guide

Tiltfile, docs/api.md
Hello @nicks,
Please review the following commits I made in branch nicks/honeycomb2:
7ee2db28a1caf6641cbe622063c18cfc39ad3c58 (2021-12-03 18:51:23 -0500)
docs: add honeycomb to api docs
=> docs: add honeycomb to api docs

src/Gemfile, src/Gemfile.lock, src/_includes/head.html, src/_layouts/docs.html, src/assets/js/links.js
Hello @hyu,
Please review the following commits I made in branch nicks/target-blank:
6f29bdf65c74b15e84ed8adcaaa0357f4c0bf181 (2021-12-07 16:20:56 -0500)
site: remove jekyll-target-blank and replace it with our own check
The jekyll-target-blank's definition of an "external" site is
non-customizable, and it doesn't seem like the upstream maintainers
are interested in fixing this.
https://github.com/keithmifsud/jekyll-target-blank/issues/45
=> site: remove jekyll-target-blank and replace it with our own check

api/api.py, src/_includes/api/functions.html
`container_selector` allows passing a container name instead of the
image to use for determining which container should be in-place
updated for Live Update.
This is useful for tools that have a predictable container name but
abstract the image details away from end users.
See tilt-dev/tilt#5248 for implementation.
=> docs: add container_selector to k8s_custom_deploy api

api/api.py
There are important differences with Python which I think are worth highlighting.
* Subdirectory names are not returned, only file names
* This function returns absolute paths, not relative to the input like Python
* Also fix typo 'rescursive'
=> Update listdir() documentation

docs/api.md, src/_data/docs.yml
Please review the following changes for the Tiltfile API section:
- Changed order of content from most to least used (assumed)
- Added navigation items to directly point to functions, types, data and extensions
=> docs: Improve navigation for Tiltfile API section

docs/index.md
Please review the following changes for the docs landing page:
- removed installation guide because I felt it didn't fit into the flow of the landingpage and there is a more extensive installation guide easily accessible from the landingpage through the navigation
- moved the "Run Tilt" section up above the explanation video
- improved wording of the "Run Tilt" section to guide users to the right manual according to their use case
=> docs: improve landingpage intro

docs/index.md, docs/tiltfile_authoring.md, docs/tutorial/index.md, src/_data/docs.yml
Please review the following changes for the Guides section:
- added new "Migrating existing projects" section to make language examples more visible and remove unwanted association with the LiveUpdate feature
=> docs: Improve access to language examples from sidebar

docs/resource_dependencies.md
Add more details to how Tilt determines readiness on k8s resources, based on feedback from #1003.
=> docs: add better detail on Kubernetes resource readiness checks

docs/example_csharp.md, docs/example_go.md, docs/example_java.md
Hello @lianmakesthings,
Please review the following commits I made in branch nicks/liveupdate:
536973ce8f877ea195b1941f78d7c04a05829c55 (2021-12-23 14:03:14 -0500)
docs: add notes about restart_process' role in live_update
=> docs: add notes about restart_process' role in live_update

src/_data/github.yml, src/assets/js/links.js
Don't consider deploy preview links from Netlify as "external" links, so they don't open in a new window. This will make sure that the deploy previews behave like the site does in local dev and prod.
=> netlify: don't open deploy preview links in new window

docs/index.md, src/_data/docs.yml, src/_data/github.yml
@SurbhiSGupta asked to move some of the more "expert" articles to a section below the tutorial.
=> docs: Change nav to prioritize tutorial

api/api.py, src/_includes/api/functions.html
1. Make sure that command parameters that accept `Union[str | List[str]]` are documented as such. (I went by calls to `ValueGroupToCmdHelper` and `ValueToUnixCmd`, but maybe there are others?)
2. Make the language around command/bat param interaction a bit more consistent.
=> docs: document List[str] possibility for all commands

src/_sass/api.scss, src/_sass/docs.scss
The negative margin extends the code block border over the next character (which is not in the code block), e.g.:
I spent a bit reading docs and haven't managed to understand the underlying issue (why is it an issue on the right but not the left? does this affect other sphinx projects?) or why this solves it (most pages I found discussing inline vs inline block indicated only differences that don't apply here, though I did find lots of handwavy references to inline-block changing the way padding is calculated wrt parent elements). It seems to work and I'm guessing it's not worth more investigation at the moment.
=> docs: fix right margin in api code blocks

api/api.py, src/_includes/api/functions.html
Hi @nicks @milas,
could you please review the following changes I made to the docs:
- Added a bit in the docker_build section to inform user that this builtin will also push to an image registry in some instances
=> docs: extend docker_build docs

docs/disable_resources.md, src/_data/docs.yml, src/_layouts/docs-mobile-nav.html, src/_layouts/docs.html, src/_sass/docs.scss
This PR adds support for adding a `pilltag` to a doc menu item and page heading. The only tag that's actually added to the live docs is the `beta` tag for the Disable Resources docs. I've removed the `new` tag next to the "Tilt API" header link.
Here are a couple screenshots of what that looks like with tags added to more places:
=> docs: add support for tags in docs menu and page titles

docs/snippets.md, src/_data/snippets/docker_build_simple.yml, src/_data/snippets/docker_compose.yml, src/_data/snippets/docker_compose_override.yml, src/_data/snippets/k8s_build_deployment.yml, src/_data/snippets/k8s_configmap.yml, src/_data/snippets/k8s_deployment.yml, src/_data/snippets/k8s_resource_config1.yml, src/_data/snippets/k8s_resource_config2.yml, src/_data/snippets/k8s_resource_port_forward.yml, src/_data/snippets/k8s_secret.yml, src/_data/snippets/k8s_yaml_custom.yml, src/_data/snippets/k8s_yaml_helm.yml, src/_data/snippets/k8s_yaml_kustomize.yml, src/_data/snippets/k8s_yaml_simple.yml, src/_data/snippets/local_go_server.yml, src/_data/snippets/local_kube_logs.yml, src/_data/snippets/local_make.yml, src/_data/snippets/local_nodejs_server.yml, src/_data/snippets/local_yarn.yml, src/_data/snippets/min_k8s_version.yml, src/_data/snippets/min_tilt_version.yml, src/_data/snippets/require_local_tool.yml, src/_data/snippets/socat.yml, src/_data/snippets/update_control_full_manual.yml, src/_data/snippets/update_control_ignore_changes.yml, src/_data/snippets/update_control_only_changes.yml, src/_sass/docs.scss
Change the YAML structure so links have both a title and href:
```
link:
title: "foo"
href: "/foo.html#bar"
```
Each snippet now shows a "References" footer with the link.
=> docs: add titles to snippet reference links

docs/api.md
Hi @nicks @nicksieger,
- updated docs to add all missing extensions
It looks like there were a lot of extensions missing. I'm wondering if there's an easier (=automated) way to do this. Maybe a CircleCI job that scrapes [the readme](https://github.com/tilt-dev/tilt-extensions/blob/master/README.md)?
=> docs: update extension overview in docs

docs/api.md, docs/snippets.md, src/_data/docs.yml
Encourage users looking at Tiltfile API to look at the snippets
page.
=> docs: add snippets link/banner to Tiltfile API

contributing-snippets.md, docs/snippets.md, src/_sass/docs.scss, src/_sass/utility.scss
Hi @hyu @SurbhiSGupta @nicksieger,
- adds a Readme, explaining how to contribute a snippet
- reference Readme in snippet library
- fixed styling, so the top content is not hidden behind header when navigating to anchor links
- moved copy-to-clipboard button away from right edge
I specifically did not include `tags` and `release_stage` in the template, since they are currently only for internal usage.
@SurbhiSGupta I also included an example design for adding a contributor's handle to a snippet. I'm 0% committed to the design, though. Interested to hear your suggestions!
=> add readme for contributing snippets

docs/dependent_images.md, docs/personal_registry.md, src/_data/docs.yml
Hello @nicksieger, @lizzthabet,
Please review the following commits I made in branch nicks/build:
e6b6220e8c89ec30ea9105a5de0ace158d39e632 (2022-02-01 11:04:57 -0500)
docs: docs on the first argument of docker_build
- Reframe the image-building doc with a more gentle intro to building a single image
- Add some notes to the registry doc about whether docker_build() should contain the registry name
=> docs: docs on the first argument of docker_build

docs/disable_resources.md
Add a short section to Disable Resources docs with instructions to disable the feature. We can remove these instructions when we have a better UI option.
=> docs: add instructions for opting out of Disable Resources feature

docs/contribute_extension.md, docs/extensions.md
Hello @landism, @nicksieger,
Please review the following commits I made in branch nicks/extensions:
43e170d3ea1424493e697ed8829c371a1e3b984f (2022-02-04 15:53:46 -0500)
docs: rewrite the extensions guide
includes all the changes from https://github.com/tilt-dev/tilt/pull/5445
on new extension download semantics
=> docs: rewrite the extensions guide

docs/api.md
The current link for `helm_resource` in the docs results in a 404. I believe the author wanted to link the extension on GitHub.
=> Fix incorrect helm_remote link

src/_sass/docs.scss
Hi @nicksieger @lizzthabet,
- added a scroll margin to the top of items in the Tiltfile & CLI section
When you navigate to an item through a permalink (e.g. https://docs.tilt.dev/api.html#api.decode_json) the upper part of the content is hidden behind the header. This PR fixes it.
It's the same issue as https://github.com/tilt-dev/tilt.build/pull/1048/commits/f53f97fe738cd7b33afdb83c00dc1fc9b4d9dcd6
=> docs: adds scroll margin to each item in function list

docs/extensions.md
Hello @landism, @lianmakesthings,
Please review the following commits I made in branch nicks/private:
b40d83a020d5890007977fd4e9e7b92ac477542d (2022-02-18 19:31:53 -0500)
docs: improve docs on pinning an extension repo
see discussion in: https://github.com/tilt-dev/tilt/issues/5522
=> docs: improve docs on pinning an extension repo

blog/_posts/2022-03-04-rancher-desktop-container-runtimes.md
I have an impressive track record with making this same mistake.
=> blog: fix typo (Docker -> Rancher)

docs/debuggers_python.md, src/_data/docs.yml
Hello @nicksieger,
Please review the following commits I made in branch nicks/debugger:
7b01ef76907c9921d794d30edebe0da9bf20e552 (2022-03-30 15:43:25 -0400)
docs: add the debugger guide back to the sidebar
=> docs: add the debugger guide back to the sidebar

src/_includes/api/functions.html
this is just a run of `make api` against head since we didn't have https://github.com/tilt-dev/tilt/pull/5657 on the last release
=> docs: rebuild api docs

docs/disable_resources.md
To correspond with [#5808](https://github.com/tilt-dev/tilt/pull/5809)
=> docs: remove support for `disable_resources` feature flag in docs

src/_includes/announce-header.html, src/_sass/header.scss, src/_sass/tilt.scss
- Also, a minor tweak to the Docker icon size
| Before | After |
| --- | --- |
| <img width="410" alt="Screen Shot 2022-05-24 at 21 19 24" src="https://user-images.githubusercontent.com/20349/170158537-0de1fad2-7e38-4dd6-85e6-f8a06c19d7cc.png"> | <img width="410" alt="Screen Shot 2022-05-24 at 21 19 12" src="https://user-images.githubusercontent.com/20349/170158540-991bf70a-879d-471a-b96e-0e64766a4ef2.png"> | 
&nbsp;
| Before | After |
| --- | --- |
| <img width="748" alt="Screen Shot 2022-05-24 at 21 21 16" src="https://user-images.githubusercontent.com/20349/170158466-d9944292-6732-494e-aa4b-a692517ac995.png"> | <img width="713" alt="Screen Shot 2022-05-24 at 21 21 08" src="https://user-images.githubusercontent.com/20349/170158487-eae5c571-63dd-4532-9432-75dd1db71898.png">  | 
&nbsp;
- …
=> site: tweak banner layout

docs/install.md
the current link https://docs.docker.com/docker-for-mac/#kubernetes is not accurate because it seems like the get-started page has changed and doesn't have the kubernetes section anymore
doing some googling it seems that this (https://docs.docker.com/desktop/kubernetes/) is the correct page
=> fixing kubernetes link from install.md

docs/example_python.md
newer versions of flask use this instead of FLASK_ENV
for live reloads
=> docs: update python example to use FLASK_DEBUG

docs/example_java.md
the openjdk image is deprecated
most oss projects seem to be moving to eclipse-temurin,
including the official java guide:
https://docs.docker.com/language/java/build-images/
=> docs: update example java dockerfile

docs/tutorial/1-prerequisites.md
This PR fixes a small typo on `docs/tutorial/1-prerequisites.md`:
`Docker Docker for Windows` => `Docker Desktop for Windows`
=> fix : a typo on `docs/tutorial/1-prerequisites.md`

contributing-snippets.md, docs/disable_resources.md, docs/multiple_repos.md
It's a common mistake: The actual brand is "Git**H**ub" as opposed to "Git**h**ub".
There was references in `/blog/_posts/*` too, but I thought they were water under the bridge and no point in changing them, but happy to apply to them as well if needed.
=> docs: update 'GitHub' brand name

docs/disable_resources.md
This seems to be referring to [Wikipedia: NOP](https://en.wikipedia.org/wiki/NOP_(code))
> In computer science, a NOP, **no-op**, or NOOP (pronounced "no op"; short for no operation) is a machine language instruction and its assembly language mnemonic, programming language statement, or computer protocol **command that does nothing**.
=> docs: fix 'no-op' term

docs/manual_update_control.md
It's referenced via inline code block in two places in the same paragraph. This one is inconsistent.
=> docs: use inline code for 'snack'

docs/editor.md
=> docs: add docs on emacs support

.github/workflows/deploy.yaml
always deploy blog and docs when src
changes, because src contains the base
templates
=> deploy: tweak deploy triggers
